### ISSUE TITLE
Check in - less than 24h hours from date shows wrong placement? 

### ISSUE THREAD

**Issue by babehboi** [jdholtz/auto-southwest-check-in#63] opened 2023-03-23 15:57 UTC
### Description

It appears that when the flight is less than 24h it either:
a) Displays the 1st flight's place in line
b) It doesn't check in the second flight appropriately

Re-ran script just in case and noticed the difference in location.

### To Reproduce

Confirmation# FName LName

With flights that are less than 24h apart.

![image](https://user-images.githubusercontent.com/125912987/227261663-496da557-1df4-4b70-add7-1434e8cfed1d.png)

### Expected Behavior

You get the same place in line.

![image](https://user-images.githubusercontent.com/125912987/227261053-3aec522a-da84-4ba1-9ebf-de76e924c063.png)

### Version

Docker Image: 3.0

**Comment by jdholtz** [comment] 2023-03-23 17:39
The first time it ran, it showed A27 for both flights. When it was ran a second time, the first flight showed A27 and the second showed A40. Is this correct? 

The messages are logged asynchronously, so that is why they are out of order. I'll make sure to fix that before closing this issue.

Could you attach your log file so I can get a closer look at what is happening? In the Docker image, it can be found at `/app/logs/auto-southwest-check-in.log`.

**Comment by babehboi** [comment] 2023-03-26 04:58
Yes you are correct! I'll try to pull the log when I arrive back at home

**Comment by jdholtz** [comment] 2023-03-26 05:26
What was the actual position you received on your boarding passes?

**Comment by babehboi** [comment] 2023-03-26 13:13
A40 was the actual position for the second flight.

So on the initial run of the script it showed A27 twice which seems like a lottery winner :p

**Comment by jdholtz** [comment] 2023-03-26 13:46
This is very strange as the last message didn't seem to get printed fully (It never said "Successfully checked in..." even though the "Passenger got A40!" message is in the same message). Unfortunately, this is hard to reproduce given the circumstances. If you had the notification service set up, were the notification messages sent correctly? Also, were you able to consistently run into this issue or did you just try it twice?

**Comment by babehboi** [comment] 2023-03-26 14:51
I decided to try it twice because I didn't believe the chancea of it checking into the same position. I don't know if the phone notification went off since I did it for a friend.

**Comment by jdholtz** [comment] 2023-03-29 01:30
I’ll close this issue for now. It seems like this was just a Python/Docker printing error since it is not clear how this could happen. I’ll reopen this if anyone else has the same issue or if there is an indication in the logs of something strange occurring.

**Closed by jdholtz** 2023-03-29 01:30 UTC
Labels: bug
