### ISSUE TITLE
Auto-southwest-check-in attempts to checkin for already traveled leg

### ISSUE THREAD

**Issue by mhardin** [jdholtz/auto-southwest-check-in#265] opened 2024-05-25 23:38 UTC
### Version

Auto-Southwest Check-In v7.4

### Browser Version

125.0.6422.76

### Description

I used this script to checkin for my flight that I traveled on 5/23.  I then tried using the script to checkin for my returning leg.  However, the script seems to think it needs to check me in for the already traveled leg on 5/23.  It runs into an error and then it won't try to automatically check me in for the flight on 5/27.  Log output below (with private details omitted)

Successful checkin for the leg on 5/23:
```
matthew@matthews-mbp auto-southwest-check-in % python3 southwest.py foo_confirmation_code matthew
Successfully scheduled the following flights to check in for matthew :
Flight from San Jose to Denver on 2024-05-23 5:30 PM PDT
Flight from Denver to San Jose on 2024-05-27 6:15 PM MDT

Checking in to flight from 'San Jose' to 'Denver' for matthew

Successfully checked in to flight from 'San Jose' to 'Denver' for matthew!
Matthew got B22!
```

Then here is the error output when trying to checkin for the 5/27 leg:
```
matthew@matthews-mbp auto-southwest-check-in % python3 southwest.py foo_confirmation_code matthew
Successfully scheduled the following flights to check in for matthew:
Flight from San Jose to Denver on 2024-05-23 5:30 PM PDT
Flight from Denver to San Jose on 2024-05-27 6:15 PM MDT

Checking in to flight from 'San Jose' to 'Denver' for matthew

Requesting error during fare check. Bad Request 400. Skipping...
Failed to check in to flight for matthew. Reason: Too Many Requests 429.
Check in at this url: https://mobile.southwest.com/check-in
```

### To Reproduce

See above, you need a flight with an already traveled leg.  The checkin script shouldn't be trying to checkin for a flight that has already been traveled.

**Comment by jdholtz** [comment] 2024-05-26 03:52
This is a duplicate of #257. The fix is on the `develop` branch. To get the fix on your machine you can run `git pull && git checkout develop`.

**Closed by jdholtz** 2024-05-26 03:52 UTC
Labels: bug

**Comment by mhardin** [comment] 2024-05-26 03:53
That’s weird.. this was reproducing when I checked out the repo this afternoon. Does that check out the develop branch by default?

**Comment by jdholtz** [comment] 2024-05-26 04:02
> Does that check out the develop branch by default?

By default you use the `master` branch which does not have the fixes yet (it only holds full releases), but I will make a release soon which will push this fix to the master branch.
