### ISSUE TITLE
Element <div data-qa="placement-link">...</div> is not clickable at point (632, 567). Other element would receive the click: <div class="backdrop visible active"></div>

### ISSUE THREAD

**Issue by gene1wood** [jdholtz/auto-southwest-check-in#318] opened 2024-11-10 17:30 UTC
### Version

https://hub.docker.com/layers/jdholtz/auto-southwest-check-in/develop/images/sha256-f3e6ded958469238603b840090e99fe86ab17aabe7751450a464fb7994b7db1f?context=explore

### Browser Version

Session info: chrome=119.0.6045.159

### Description

When launching the [`develop` branch of the docker container](https://hub.docker.com/layers/jdholtz/auto-southwest-check-in/develop/images/sha256-f3e6ded958469238603b840090e99fe86ab17aabe7751450a464fb7994b7db1f?context=explore) with a single confirmation number/name combo, it shows this error

```
Monitoring 0 accounts and 1 reservation

Process Process-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
 self.run()
File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
 self._target(*self._args, **self._kwargs)
File "/app/lib/reservation_monitor.py", line 54, in monitor
 self._monitor()
File "/app/lib/reservation_monitor.py", line 72, in _monitor
 should_exit = self._check()
               ^^^^^^^^^^^^^
File "/app/lib/reservation_monitor.py", line 93, in _check
 self.checkin_scheduler.refresh_headers()
File "/app/lib/checkin_scheduler.py", line 50, in refresh_headers
 webdriver.set_headers()
File "/app/lib/webdriver.py", line 86, in set_headers
 driver = self._get_driver()
          ^^^^^^^^^^^^^^^^^^
File "/app/lib/webdriver.py", line 159, in _get_driver
 driver.click("(//div[@data-qa='placement-link'])[2]")
File "/app/.local/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 74, in click
 page_actions.click(self.driver, *args, **kwargs)
File "/app/.local/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 1595, in click
 element.click()
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
 self._execute(Command.CLICK_ELEMENT)
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
 return self._parent.execute(command, params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
 self.error_handler.check_response(response)
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
 raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div data-qa="placement-link">...</div> is not clickable at point (632, 567). Other element would receive the click: <div class="backdrop visible active"></div>
(Session info: chrome=119.0.6045.159)
```

### To Reproduce

1. Launch the current [`develop` branch of the docker container](https://hub.docker.com/layers/jdholtz/auto-southwest-check-in/develop/images/sha256-f3e6ded958469238603b840090e99fe86ab17aabe7751450a464fb7994b7db1f?context=explore) with a docker-compose like this

```
services:
  auto-southwest:
    image: dmytrokoren/auto-southwest-check-in:develop
    container_name: auto-southwest
    restart: on-failure
    environment:
      - AUTO_SOUTHWEST_CHECK_IN_NOTIFICATION_URL=ntfys://jcGetqPYT9QVz8/
      - AUTO_SOUTHWEST_CHECK_IN_CONFIRMATION_NUMBER=123ABC
      - AUTO_SOUTHWEST_CHECK_IN_FIRST_NAME=First
      - AUTO_SOUTHWEST_CHECK_IN_LAST_NAME=Last
      - AUTO_SOUTHWEST_CHECK_IN_CHECK_FARES=false
```

### Expected Behavior

Not erroring out and exiting

### Relevant logs and program output

```sh
Monitoring 0 accounts and 1 reservation

Process Process-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
 self.run()
File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
 self._target(*self._args, **self._kwargs)
File "/app/lib/reservation_monitor.py", line 54, in monitor
 self._monitor()
File "/app/lib/reservation_monitor.py", line 72, in _monitor
 should_exit = self._check()
               ^^^^^^^^^^^^^
File "/app/lib/reservation_monitor.py", line 93, in _check
 self.checkin_scheduler.refresh_headers()
File "/app/lib/checkin_scheduler.py", line 50, in refresh_headers
 webdriver.set_headers()
File "/app/lib/webdriver.py", line 86, in set_headers
 driver = self._get_driver()
          ^^^^^^^^^^^^^^^^^^
File "/app/lib/webdriver.py", line 159, in _get_driver
 driver.click("(//div[@data-qa='placement-link'])[2]")
File "/app/.local/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 74, in click
 page_actions.click(self.driver, *args, **kwargs)
File "/app/.local/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 1595, in click
 element.click()
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
 self._execute(Command.CLICK_ELEMENT)
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
 return self._parent.execute(command, params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
 self.error_handler.check_response(response)
File "/app/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
 raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div data-qa="placement-link">...</div> is not clickable at point (632, 567). Other element would receive the click: <div class="backdrop visible active"></div>
(Session info: chrome=119.0.6045.159)
```

**Comment by jdholtz** [comment] 2024-11-11 00:11
Hey @gene1wood, this is a duplicate of #312. Even though the issue is for v8.0, it is present in v8.1 as well.

**Closed by jdholtz** 2024-11-11 00:11 UTC
Labels: bug
