### ISSUE TITLE
v3.1: Timed out receiving message from renderer from Docker

### ISSUE THREAD

**Issue by pldimarco** [jdholtz/auto-southwest-check-in#67] opened 2023-03-26 11:10 UTC
### Description

When attempting to run v3.1 version of the docker, I am presented with the following stack trace:
```
2023-03-26 10:55:52 DEBUG MainProcess[log]: Initialized the application
2023-03-26 10:55:52 DEBUG MainProcess[main]: Called with 1 arguments
2023-03-26 10:55:53 DEBUG MainProcess[config]: Reading the configuration file
2023-03-26 10:55:53 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-03-26 10:55:53 DEBUG MainProcess[config]: Adding 1 flights from configuration file
2023-03-26 10:55:53 DEBUG MainProcess[config]: Setting notification level to 1
2023-03-26 10:55:53 DEBUG MainProcess[config]: Using 1 notification services
2023-03-26 10:55:53 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-03-26 10:55:53 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-03-26 10:55:53 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 10:55:53 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 10:55:53 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-03-26 10:55:53 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-03-26 10:55:54 DEBUG Process-1[webdriver]: Loading Southwest Check-In page
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/flight_retriever.py", line 37, in schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/app/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 60, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 149, in _get_driver
    driver.get(CHECKIN_URL)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 656, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.000
  (Session info: chrome=110.0.5481.177)
```

I have seen it work once for one flight, so it seems to be an intermittent issue. But with multiple flights, it seems to happen consistently. Going back to v3.0 works fine.

### To Reproduce

1. Set a config file with multiple flight confirmationNumber/firstName/lastName entries
2. Run `docker run --volume /.../config.json:/app/config.json jdholtz/auto-southwest-check-in:v3.1 -- --verbose`

### Expected Behavior

The embedded browser able to get to the check-in page.

### Version

v3.1

**Comment by jdholtz** [comment] 2023-03-26 13:14
Hi. Thanks for filing this issue! I was able to test on multiple machines with three different flights each, but unfortunately I couldn't reproduce this. However, I was able to get the same StackTrace by setting the page load timeout very low so that might be the issue. How long did it take between printing the last log message and throwing the StackTrace?

Since I can't reproduce the issue, would you be able to try a potential fix I have? I'll give you directions on how to add the fix in the container, but let me know if you just want me to put the new changes on the `develop` image.

1. Override the container entrypoint to sleep infinity: `docker run --detach --volume ... --entrypoint sleep jdholtz/auto-southwest-check-in:v3.1 infinity`
2. Go into the container: `docker exec -it <container_name> sh`
3. Add the following on line 146 of lib/webdriver.py: driver.set_page_load_timeout(3000). Use vi as the text editor: `vi lib/webdriver.py`
4. Run the script: `python southwest.py`

The default page load timeout is 300 seconds, so I'd be very surprised if it hits that limit.

**Comment by pldimarco** [comment] 2023-03-26 14:24
@jdholtz I performed the instructions you gave. I ran the script with 4 flights, of which 1 successfully checked in and posted it's sleep until check-in time. The other 3 gave no output past `Refreshing headers for current session`. I waited a while for updated logs before stopping the process. I could have let the container run, but the stack trace doesn't give a timestamp like above. So I figured, it may not express how long it took. Logs (sub 50 minutes like your suggested timeout):

```
/app # python southwest.py --verbose
2023-03-26 14:14:06 DEBUG MainProcess[log]: Initialized the application
2023-03-26 14:14:06 DEBUG MainProcess[main]: Called with 0 arguments
2023-03-26 14:14:06 DEBUG MainProcess[config]: Reading the configuration file
2023-03-26 14:14:06 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-03-26 14:14:06 DEBUG MainProcess[config]: Adding 4 flights from configuration file
2023-03-26 14:14:06 DEBUG MainProcess[config]: Setting notification level to 1
2023-03-26 14:14:06 DEBUG MainProcess[config]: Using 1 notification services
2023-03-26 14:14:06 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-03-26 14:14:06 DEBUG MainProcess[main]: Monitoring 0 accounts and 4 flights
2023-03-26 14:14:06 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 14:14:06 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 14:14:06 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-03-26 14:14:06 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-03-26 14:14:06 DEBUG Process-2[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 14:14:06 DEBUG Process-2[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 14:14:06 DEBUG Process-2[checkin_scheduler]: Refreshing headers for current session
2023-03-26 14:14:06 DEBUG Process-2[webdriver]: Starting webdriver for current session
2023-03-26 14:14:06 DEBUG Process-3[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 14:14:06 DEBUG Process-3[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 14:14:06 DEBUG Process-3[checkin_scheduler]: Refreshing headers for current session
2023-03-26 14:14:06 DEBUG Process-3[webdriver]: Starting webdriver for current session
2023-03-26 14:14:06 DEBUG Process-4[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 14:14:06 DEBUG Process-4[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 14:14:06 DEBUG Process-4[checkin_scheduler]: Refreshing headers for current session
2023-03-26 14:14:06 DEBUG Process-4[webdriver]: Starting webdriver for current session
2023-03-26 14:14:07 DEBUG Process-1[webdriver]: Loading Southwest Check-In page
2023-03-26 14:14:07 DEBUG Process-2[webdriver]: Loading Southwest Check-In page
2023-03-26 14:15:18 DEBUG Process-2[webdriver]: Filling out a check-in form to get valid headers
2023-03-26 14:15:29 DEBUG Process-2[webdriver]: Setting valid headers from previous request
2023-03-26 14:15:29 DEBUG Process-2[checkin_scheduler]: Retrieving reservation info from confirmation number
2023-03-26 14:15:30 DEBUG Process-2[general]: Successfully made request after 0 attempts
2023-03-26 14:15:30 DEBUG Process-2[checkin_scheduler]: Successfully retrieved reservation info
2023-03-26 14:15:30 DEBUG Process-2[checkin_scheduler]: 2 flights found under current reservation
2023-03-26 14:15:30 DEBUG Process-2[checkin_scheduler]: New flight found. Handling check-in
2023-03-26 14:15:30 DEBUG Process-2[checkin_handler]: Scheduling check-in for current flight
2023-03-26 14:15:30 DEBUG Process-2:1[checkin_handler]: Sleeping until ten minutes before check-in...
2023-03-26 14:15:30 DEBUG Process-2[checkin_scheduler]: New flight found. Handling check-in
2023-03-26 14:15:30 DEBUG Process-2[checkin_handler]: Scheduling check-in for current flight
2023-03-26 14:15:30 DEBUG Process-2[notification_handler]: Sending new flights notification
Successfully scheduled the following flights to check in for {REDACTED}:
Flight from {REDACTED}
Flight from {REDACTED}

2023-03-26 14:15:30 DEBUG Process-2:2[checkin_handler]: Sleeping until ten minutes before check-in...
```

Maybe we can put a try/catch around the process to at least timestamp the stack trace?

**Comment by jdholtz** [comment] 2023-03-26 14:56
Thanks for testing. It seems that the page just never loads. Here is a few more things you can try:

- Delete [line 165](https://github.com/jdholtz/auto-southwest-check-in/blob/4c06e082d9ac672cd4a639ea377196a3d3ee9375/lib/webdriver.py#L165)
- Add `options.page_load_strategy = "eager"` on line 166. Also try with "none" instead of "eager"

**Comment by pldimarco** [comment] 2023-03-26 17:13
I deleted the line. With `page_load_strategy = "eager"` I saw no difference. With `page_load_strategy = "none"`, it got "further", but right into another error. Logs from `none` run:
```
/app # python southwest.py --verbose
2023-03-26 17:10:52 DEBUG MainProcess[log]: Initialized the application
2023-03-26 17:10:52 DEBUG MainProcess[main]: Called with 0 arguments
2023-03-26 17:10:53 DEBUG MainProcess[config]: Reading the configuration file
2023-03-26 17:10:53 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-03-26 17:10:53 DEBUG MainProcess[config]: Adding 4 flights from configuration file
2023-03-26 17:10:53 DEBUG MainProcess[config]: Setting notification level to 1
2023-03-26 17:10:53 DEBUG MainProcess[config]: Using 1 notification services
2023-03-26 17:10:53 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-03-26 17:10:53 DEBUG MainProcess[main]: Monitoring 0 accounts and 4 flights
2023-03-26 17:10:53 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 17:10:53 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 17:10:53 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-03-26 17:10:53 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-03-26 17:10:53 DEBUG Process-2[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 17:10:53 DEBUG Process-2[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 17:10:53 DEBUG Process-2[checkin_scheduler]: Refreshing headers for current session
2023-03-26 17:10:53 DEBUG Process-2[webdriver]: Starting webdriver for current session
2023-03-26 17:10:53 DEBUG Process-3[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 17:10:53 DEBUG Process-3[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 17:10:53 DEBUG Process-3[checkin_scheduler]: Refreshing headers for current session
2023-03-26 17:10:53 DEBUG Process-3[webdriver]: Starting webdriver for current session
2023-03-26 17:10:53 DEBUG Process-4[flight_retriever]: Scheduling reservations for 1 flights
2023-03-26 17:10:53 DEBUG Process-4[checkin_scheduler]: No headers set. Refreshing...
2023-03-26 17:10:53 DEBUG Process-4[checkin_scheduler]: Refreshing headers for current session
2023-03-26 17:10:53 DEBUG Process-4[webdriver]: Starting webdriver for current session
2023-03-26 17:10:53 DEBUG Process-1[webdriver]: Loading Southwest Check-In page
2023-03-26 17:10:53 DEBUG Process-3[webdriver]: Loading Southwest Check-In page
2023-03-26 17:10:53 DEBUG Process-1[webdriver]: Filling out a check-in form to get valid headers
2023-03-26 17:10:53 DEBUG Process-3[webdriver]: Filling out a check-in form to get valid headers
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/flight_retriever.py", line 37, in schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/app/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 64, in set_headers
    confirmation_element = WebDriverWait(driver, 30).until(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by jdholtz** [comment] 2023-03-26 17:21
I appreciate you testing this extensively. The new error indicates that an element on the webpage never actually loaded.

Is it possible to test the script on your local machine? It would be good to know if this is only an issue with the Docker container and not your host machine’s network settings.

**Comment by pldimarco** [comment] 2023-03-27 12:26
So I checked out the `v3.1` tag locally. I looked at the python version in the container is at `3.11.2`. The latest on `pyenv` is `3.11.0`, so I used that version. The script ran fine locally.

**Comment by jdholtz** [comment] 2023-03-27 16:38
Unfortunately, I am out of ideas to understand why this is behavior is occurring. You can see if you can get Chromium to run in the image by calling it directly. It also could be a limited amount of memory or different network settings that the container has (I'm not too sure how a Docker container uses resources though). 

The best option would be to wait for a few days to see if anyone else has this issue.

**Comment by jdholtz** [comment] 2023-03-27 18:53
I did change the Docker image quite significantly in v3.1. The two major changes were using Chromium instead of Google Chrome and Alpine Linux instead of Ubuntu.

**Comment by jdholtz** [comment] 2023-03-29 01:34
@pldimarco you can try to increase the container’s resources as indicated [here](https://docs.docker.com/config/containers/resource_constraints/). Since it worked on your host machine and another Docker host, it doesn’t appear that there is an issue with the script itself.

**Comment by pldimarco** [comment] 2023-03-30 15:26
@jdholtz I don't see anything on that page about increasing limits, it seems to be around limiting resource consumption. I could try stopping more containers on my docker host to see if that frees up some memory. But I think we're in the right direction anyway as I've had some `kswapd` spikes recently. So am picking up some additional ram for the system. After that arrives I will give this another go to see if that resolves the issue. Thanks for the help!

**Comment by ctkubik** [comment] 2023-03-30 18:57
I'm a complete noob when it comes to Docker for Windows, but I managed to get the container running and everything was beautiful for a few days.  When my system went to update itineraries for logged in accounts I started getting the errors in this message.  I have 3 accounts in my config file to log into.  This time around the first account logged in successfully...the other two didn't.

2023-03-30 11:52:55 Process Process-2:
2023-03-30 11:52:55 Process Process-3:
2023-03-30 11:52:55 Traceback (most recent call last):
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2023-03-30 11:52:55     self.run()
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2023-03-30 11:52:55     self._target(*self._args, **self._kwargs)
2023-03-30 11:52:55   File "/app/lib/flight_retriever.py", line 64, in monitor_account
2023-03-30 11:52:55     flights = self._get_flights()
2023-03-30 11:52:55               ^^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/flight_retriever.py", line 85, in _get_flights
2023-03-30 11:52:55     flights = webdriver.get_flights(self)
2023-03-30 11:52:55               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/webdriver.py", line 90, in get_flights
2023-03-30 11:52:55     driver = self._get_driver()
2023-03-30 11:52:55              ^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/webdriver.py", line 140, in _get_driver
2023-03-30 11:52:55     driver = Chrome(
2023-03-30 11:52:55              ^^^^^^^
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
2023-03-30 11:52:55     super().__init__(*args, **kwargs)
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
2023-03-30 11:52:55     super(Chrome, self).__init__(
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
2023-03-30 11:52:55     super().__init__(
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
2023-03-30 11:52:55     self.service.start()
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 88, in start
2023-03-30 11:52:55     self._start_process(self.path)
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 195, in _start_process
2023-03-30 11:52:55     self.process = subprocess.Popen(
2023-03-30 11:52:55                    ^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
2023-03-30 11:52:55     self._execute_child(args, executable, preexec_fn, close_fds,
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
2023-03-30 11:52:55     raise child_exception_type(errno_num, err_msg, err_filename)
2023-03-30 11:52:55 OSError: [Errno 26] Text file busy: '/usr/bin/chromedriver'
2023-03-30 11:52:55 Traceback (most recent call last):
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2023-03-30 11:52:55     self.run()
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2023-03-30 11:52:55     self._target(*self._args, **self._kwargs)
2023-03-30 11:52:55   File "/app/lib/flight_retriever.py", line 64, in monitor_account
2023-03-30 11:52:55     flights = self._get_flights()
2023-03-30 11:52:55               ^^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/flight_retriever.py", line 85, in _get_flights
2023-03-30 11:52:55     flights = webdriver.get_flights(self)
2023-03-30 11:52:55               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/webdriver.py", line 90, in get_flights
2023-03-30 11:52:55     driver = self._get_driver()
2023-03-30 11:52:55              ^^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/app/lib/webdriver.py", line 140, in _get_driver
2023-03-30 11:52:55     driver = Chrome(
2023-03-30 11:52:55              ^^^^^^^
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
2023-03-30 11:52:55     super().__init__(*args, **kwargs)
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
2023-03-30 11:52:55     super(Chrome, self).__init__(
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
2023-03-30 11:52:55     super().__init__(
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
2023-03-30 11:52:55     self.service.start()
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 88, in start
2023-03-30 11:52:55     self._start_process(self.path)
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 195, in _start_process
2023-03-30 11:52:55     self.process = subprocess.Popen(
2023-03-30 11:52:55                    ^^^^^^^^^^^^^^^^^
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
2023-03-30 11:52:55     self._execute_child(args, executable, preexec_fn, close_fds,
2023-03-30 11:52:55   File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
2023-03-30 11:52:55     raise child_exception_type(errno_num, err_msg, err_filename)
2023-03-30 11:52:55 OSError: [Errno 26] Text file busy: '/usr/bin/chromedriver'
2023-03-30 11:53:16 Successfully logged in to XXXXXXXXXXXXXX account
2023-03-30 11:53:16 
2023-03-30 11:53:25 Successfully scheduled the following flights to check in for XXXXXXXXXXX:
2023-03-30 11:53:25 Flight from XXX
2023-03-30 11:53:25 Flight from XXXXX
2023-03-30 11:53:25 Flight from XXXXXXX
2023-03-30 11:53:25 Flight from XXXXXX
2023-03-30 11:53:25 Flight from XXXXXX
2023-03-30 11:53:25 Flight from XXXXXXX
2023-03-30 11:53:25

**Comment by jdholtz** [comment] 2023-03-30 22:11
@ctkubik does this error happen repeatedly? This issue seems to occur because of the way undetected_chromedriver handles starting multiple drivers (and that project has been inactive since February unfortunately). Currently, I don't have very good resilience against running the script for long-term, but I will be adding those soon.

**Comment by ctkubik** [comment] 2023-03-30 22:41
Oddly enough...it if I restart the container over and over it will eventually log each account in again.  I'm checking my mom in in a flight on Saturday...should I register the flight alone or try it this way?

**Comment by jdholtz** [comment] 2023-03-30 23:21
You can try doing it in the same container, but the most reliable way would be to just use a separate container for that flight.

**Comment by ctkubik** [comment] 2023-03-30 23:29
Perfect.  I will try that tomorrow.  I have no idea what I am doing with Docker, but it's a fun challenge.

**Comment by jdholtz** [comment] 2023-04-12 12:12
@pldimarco I will close this issue for now since you are able to get the script working on other machines. Let me know if the issue occurs after troubleshooting the potential OOM issue.

**Closed by jdholtz** 2023-04-12 12:12 UTC
Labels: bug
