### ISSUE TITLE
Dockerfile build error on ARM architecture

### ISSUE THREAD

**Issue by teamjoetv** [jdholtz/auto-southwest-check-in#27] opened 2022-12-15 07:51 UTC
I've been trying to run docker on my ubuntu server, but seeing a gpg key issue. Below is a log.

$ docker build -f Dockerfile . -t auto-southwest-check-in

------------------------------------------------------------------------------------------------
.
.
.
Step 5/10 : RUN wget https://dl-ssl.google.com/linux/linux_signing_key.pub -O /tmp/google.pub &&     gpg --no-default-keyring --keyring /etc/apt/keyrings/google-chrome.gpg --import /tmp/google.pub &&     echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' |     tee /etc/apt/sources.list.d/google-chrome.list
 ---> Running in 37cd582cfe2d
--2022-12-14 17:38:36--  https://dl-ssl.google.com/linux/linux_signing_key.pub
Resolving dl-ssl.google.com (dl-ssl.google.com)... 74.125.137.91, 74.125.137.190, 74.125.137.93, ...
Connecting to dl-ssl.google.com (dl-ssl.google.com)|74.125.137.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12415 (12K) [application/octet-stream]
Saving to: '/tmp/google.pub'
0K .......... ..                                         100% 4.48M=0.003s

2022-12-14 17:38:36 (4.48 MB/s) - '/tmp/google.pub' saved [12415/12415]

gpg: keybox '/etc/apt/keyrings/google-chrome.gpg' created
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key A040830F7FAC5991: public key "Google, Inc. Linux Package Signing Key <linux-packages-keymaster@google.com>" imported
gpg: key 7721F63BD38B4796: 1 signature not checked due to a missing key
gpg: key 7721F63BD38B4796: public key "Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2
gpg: no ultimately trusted keys found
deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
Removing intermediate container 37cd582cfe2d
 ---> 69f8d041bb25
.
.
.
.
Reading state information...
E: Unable to locate package google-chrome-stable
The command '/bin/sh -c apt-get update && apt-get -y install google-chrome-stable' returned a non-zero code: 100

------------------------------------------------------------------------------------------------
Any suggestions to resolve that issue? Thanks!

**Comment by jdholtz** [comment] 2022-12-15 13:51
Hey. Thanks for filing this issue. 

I'm not able to reproduce this error when rebuilding the Docker image on my machine. What OS are you using? And what Docker version do you currently have?

**Comment by teamjoetv** [comment] 2022-12-15 18:21
Ubuntu 20.04.2 LTS
Docker version 20.10.7, build f0df350

Those are my environment.

**Comment by jdholtz** [comment] 2022-12-15 20:58
Can you add the `--platform linux/amd64` flag to your docker build command and see if it works? You might need to add the `--no-cache` flag as well just in case it tries to use the cache

**Comment by teamjoetv** [comment] 2022-12-16 06:14
Just tried to run docker with that flags and still have no luck. It keeps giving me the same error.

**Comment by jdholtz** [comment] 2022-12-16 11:18
Huh. Since I can’t reproduce the error, I’m going to be of little help. If you want, you can try to fix this issue and submit a PR. Some other things to try are updating the Ubuntu base image (if it is isn’t the latest version from last week) and upgrading your Docker version. 

I do get the same GPG log that you are getting in the `docker build` phase, but it still finds the package to install Google Chrome (maybe there are other logs?). 

If anyone else sees this and is running into the same issue, please let me know here.

**Comment by teamjoetv** [comment] 2022-12-16 21:30
I just tried on the other ubuntu servers and on my mac, it works like a charm, however the issue only happens when I try to install it on ubuntu on OCI (It's oracle cloud. Maybe they block to use chrome. I don't know..). Will spend some time to modify and install with the Dockerfile and let you know. Thanks!

**Comment by teamjoetv** [comment] 2022-12-16 22:10
Just found this.  
https://askubuntu.com/questions/1383789/install-chrome-on-ubuntu-debian-with-arm64

Yeah it seems ubuntu on the oracle cloud is ARM. Do you think your beautiful code works with Chromium instead Chrome? Sorry that I am really bugging you. :-)

**Comment by jdholtz** [comment] 2022-12-16 23:21
Hey. Glad you pinpointed what the issue was. 

You can try to download Chromium in Docker instead of google-chrome. This script uses [undetected_chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) to stay undetected by Southwest’s API and it should work with any Chromium-based browser without any code changes in this script (although I haven’t tested so I am not certain).

**Comment by jdholtz** [comment] 2022-12-25 15:07
Since I do not have ARM architecture to test with, this will need to be fixed by someone else. To do this, either another Dockerfile can be created or multi-staged builds can be created within the same Dockerfile.

However, Google Chrome is not supported on ARM architecture, so this script will also have to support Chromium (which it should already, but I have not tested).

**Comment by Connor-8** [comment] 2023-01-01 07:16
This command worked for me

`docker build -f Dockerfile . -t auto-southwest-check-in --platform linux/amd64`

**Comment by jdholtz** [comment] 2023-03-20 18:52
Unfortunately, using that platform flag won’t actually work because the image is built for a different architecture (that was my mistake suggesting that). I have a Raspberry Pi I will be able to test this with, so I will be working on a fix soon

**Comment by hgrias** [comment] 2023-03-21 17:04
I was previously able to run the image on a previous computer (Macbook Pro M1 - so ARM arch). I remember it did take some work to do - most likely with docker buildx and building a x86 image with rosetta/virtualization. I unfortunately can't remember what I did to make it run, but will report back here if I do get it running again!

**Comment by jdholtz** [comment] 2023-03-25 20:10
The ARM Docker image is currently available under the `:develop` tag. Can someone pull this to verify it runs on their ARM system too? After that, I will close this issue and release a new version.

**Comment by hgrias** [comment] 2023-03-25 20:55
Was able to pull the image and run. Unfortunately I don't have a flight planned to fully test, but was able to authenticate with my username and password!

**Comment by jdholtz** [comment] 2023-03-25 21:13
Awesome! Thanks for testing it.

**Closed by jdholtz** 2023-03-25 21:13 UTC
Labels: help wanted
