### ISSUE TITLE
Continuously hitting 403 error

### ISSUE THREAD

**Issue by osharif123** [jdholtz/auto-southwest-check-in#242] opened 2024-03-20 05:38 UTC
### Version

7.3

### Browser Version

Google Chrome 124.0.6356.2 dev

### Description

uc_driver = 124.0.6367.2
I am running the script on an amazon linux 2023 image on aws. I have been consistently running into a 403 error everytime I run the script (regardless of whether it's via docker or directly on my machine. I updated my config file to have two confirmation numbers (for 2 passengers). Best case scenario is that I will have one passenger successfully scheduled and the other fails:
```Successfully scheduled the following flights to check in for John Doe:
Flight from Chicago to Miami at 2024-04-03 9:35 AM CDT
Flight from Miami to Chicago at 2024-04-13 9:25 AM EDT

Failed to retrieve reservation for Jane Doe with confirmation number ABC123. Reason: Forbidden 403.
Make sure the reservation information is correct and try again.```

I have had both users get successfully scheduled but never at the same time, or they both fail. I have also failed with just one passenger. I have considered if I might be getting rate limited and tried from multiple different IPs. 

### To Reproduce

1. Update config.json to include reservation details.
2. Run python3 southwest.py
3. view error

### Expected Behavior

_No response_

### Relevant logs and program output

_No response_

### Additional context

_No response_

**Comment by jdholtz** [comment] 2024-03-20 05:45
Duplicate of #230.

**Closed by jdholtz** 2024-03-20 05:45 UTC
Labels: bug
