### ISSUE TITLE
Element click intercepted: Login Button is not clickable (Docker)

### ISSUE THREAD

**Issue by dmytrokoren** [jdholtz/auto-southwest-check-in#226] opened 2024-02-16 15:13 UTC
### Version

Auto-Southwest Check-In v7.2 (develop branch)

### Browser Version

chrome=121.0.6167.184

### Description

Getting an error unable to click login button and the container auto stops due to failure.
Error:
element click intercepted: Element <span class="login-button--box">...</span> is not clickable at point (1369, 29)

Note: I ran this in Terminal and it's working as expected I'm not sure why Docker is not working.

### To Reproduce

Run docker with config.json using accounts

### Expected Behavior

Should be successfully logged in.

### Relevant logs and program output

```sh
2024/02/15 23:39:48 | stdout | (Session info: chrome=121.0.6167.184)
-- | -- | --
2024/02/15 23:39:48 | stdout | selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="login-button--box">...</span> is not clickable at point (1369, 29). Other element would receive the click: <div class="backdrop visible active"></div>
2024/02/15 23:39:48 | stdout | raise exception_class(message, screen, stacktrace)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024/02/15 23:39:48 | stdout | self.error_handler.check_response(response)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
2024/02/15 23:39:48 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/02/15 23:39:48 | stdout | return self._parent.execute(command, params)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
2024/02/15 23:39:48 | stdout | self._execute(Command.CLICK_ELEMENT)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
2024/02/15 23:39:48 | stdout | element.click()
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 1526, in click
2024/02/15 23:39:48 | stdout | page_actions.click(self.driver, *args, **kwargs)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 59, in click
2024/02/15 23:39:48 | stdout | driver.click(".login-button--box")
2024/02/15 23:39:48 | stdout | File "/app/lib/webdriver.py", line 83, in get_reservations
2024/02/15 23:39:48 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/02/15 23:39:48 | stdout | reservations = webdriver.get_reservations(self)
2024/02/15 23:39:48 | stdout | File "/app/lib/reservation_monitor.py", line 182, in _get_reservations
2024/02/15 23:39:48 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^
2024/02/15 23:39:48 | stdout | reservations, skip_scheduling = self._get_reservations()
2024/02/15 23:39:48 | stdout | File "/app/lib/reservation_monitor.py", line 157, in _monitor
2024/02/15 23:39:48 | stdout | self._monitor()
2024/02/15 23:39:48 | stdout | File "/app/lib/reservation_monitor.py", line 42, in monitor
2024/02/15 23:39:48 | stdout | self._target(*self._args, **self._kwargs)
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
2024/02/15 23:39:48 | stdout | self.run()
2024/02/15 23:39:48 | stdout | File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
2024/02/15 23:39:48 | stdout | Traceback (most recent call last):
2024/02/15 23:39:47 | stdout | Process Process-3:
2024/02/15 23:39:46 | stdout | 2024-02-16 05:39:46 DEBUG Process-3[webdriver:79]: Logging into account to get a list of reservations and valid headers
2024/02/15 23:39:11 | stdout | 2024-02-16 05:39:10 DEBUG Process-3[webdriver:121]: Loading Southwest Check-In page
2024/02/15 23:39:10 | stdout | 2024-02-16 05:39:10 DEBUG Process-3[webdriver:117]: Using browser version: 121.0.6167.184
```

**Comment by bradzab0623** [comment] 2024-02-16 15:55
I am seeing this now as well

**Comment by FrankGasparovic** [comment] 2024-02-16 17:19
I am seeing this as well. Running on the develop docker image in docker.

**Comment by jdholtz** [comment] 2024-02-16 20:15
Fixed in the latest develop commit. I was able to reproduce it in Docker as well. 

There was a pop-up coming up that said "Something must have gone wrong. Please try again". Not sure why that was appearing, but clicking "OK" removes the pop-up and everything continues as normal. This is probably due to another one of their changes and may be fixed later, but I'll keep it in case this issue ever comes up again.

**Comment by dmytrokoren** [comment] 2024-02-16 20:18
> Fixed in the latest develop commit. I was able to reproduce it in Docker as well. 
> 
> 
> 
> There was a pop-up coming up that said "Something must have gone wrong. Please try again". Not sure why that was appearing, but clicking "OK" removes the pop-up and everything continues as normal. This is probably due to another one of their changes and may be fixed later, but I'll keep it in case this issue ever comes up again.

@jdholtz I can use develop branch in docker? Is your new changes pushed to docker hub?

**Comment by jdholtz** [comment] 2024-02-16 20:23
> @jdholtz I can use develop branch in docker? Is your new changes pushed to docker hub?

Yes, whenever there are changes to the develop branch, a Docker image automatically gets pushed to Docker hub within a few minutes.

**Comment by bradzab0623** [comment] 2024-02-16 20:29
I'm now getting the following using the new develop docker image. Successfully logs in and then 403s getting the reservations....odd

```
2024-02-16 20:26:30 DEBUG Process-1[webdriver:233]: First time logging in. Setting account name
Successfully logged in to Jessica Zabinski's account

2024-02-16 20:26:30 DEBUG Process-1[webdriver:155]: Waiting for trips_request_id to be set
2024-02-16 20:26:31 DEBUG Process-1[webdriver:151]: Upcoming trips response has been received
2024-02-16 20:26:32 DEBUG Process-1[webdriver:159]: trips_request_id set successfully
2024-02-16 20:26:32 DEBUG Process-1[reservation_monitor:209]: Successfully retrieved 3 reservations
2024-02-16 20:26:32 DEBUG Process-1[reservation_monitor:84]: Scheduling flight check-ins for 3 reservations
2024-02-16 20:26:32 DEBUG Process-1[checkin_scheduler:76]: Retrieving reservation information
2024-02-16 20:26:47 DEBUG Process-1[utils:39]: Failed to make request after 20 attempts: Forbidden 403
2024-02-16 20:26:47 DEBUG Process-1[utils:42]: Response body: {
  "code": 403050700
}
2024-02-16 20:26:47 DEBUG Process-1[checkin_scheduler:82]: Failed to retrieve reservation info. Error: Forbidden 403. Exiting
2024-02-16 20:26:47 DEBUG Process-1[notification_handler:76]: Sending failed reservation retrieval notification...
Failed to retrieve reservation for Jessica Zabinski with confirmation number <confirm num>. Reason: Forbidden 403.
Make sure the reservation information is correct and try again.
```

**Comment by jdholtz** [comment] 2024-02-16 20:36
That pop-up must mean that something actually did go wrong, so I guess it can't be ignored. I'll reopen this. Unfortunately, I don't have any flights to test with right now.

@bradzab0623 does the same thing happen when you use a reservation instead of an account?

**Comment by dmytrokoren** [comment] 2024-02-16 20:37
I'm all set its working for me in Docker.

![CleanShot 2024-02-16 at 14 35 45@2x](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/17661653-c369-41b9-baa8-2a0ec5d45504)

**Comment by dmytrokoren** [comment] 2024-02-16 20:39
> I'm now getting the following using the new develop docker image. Successfully logs in and then 403s getting the reservations....odd
> 
> ```
> 2024-02-16 20:26:30 DEBUG Process-1[webdriver:233]: First time logging in. Setting account name
> Successfully logged in to Jessica Zabinski's account
> 
> 2024-02-16 20:26:30 DEBUG Process-1[webdriver:155]: Waiting for trips_request_id to be set
> 2024-02-16 20:26:31 DEBUG Process-1[webdriver:151]: Upcoming trips response has been received
> 2024-02-16 20:26:32 DEBUG Process-1[webdriver:159]: trips_request_id set successfully
> 2024-02-16 20:26:32 DEBUG Process-1[reservation_monitor:209]: Successfully retrieved 3 reservations
> 2024-02-16 20:26:32 DEBUG Process-1[reservation_monitor:84]: Scheduling flight check-ins for 3 reservations
> 2024-02-16 20:26:32 DEBUG Process-1[checkin_scheduler:76]: Retrieving reservation information
> 2024-02-16 20:26:47 DEBUG Process-1[utils:39]: Failed to make request after 20 attempts: Forbidden 403
> 2024-02-16 20:26:47 DEBUG Process-1[utils:42]: Response body: {
>   "code": 403050700
> }
> 2024-02-16 20:26:47 DEBUG Process-1[checkin_scheduler:82]: Failed to retrieve reservation info. Error: Forbidden 403. Exiting
> 2024-02-16 20:26:47 DEBUG Process-1[notification_handler:76]: Sending failed reservation retrieval notification...
> Failed to retrieve reservation for Jessica Zabinski with confirmation number <confirm num>. Reason: Forbidden 403.
> Make sure the reservation information is correct and try again.
> ```

Agh.. I guess this is an issue with reservations. Unfortunately I do not have any reservations to check in.

**Comment by bradzab0623** [comment] 2024-02-16 20:44
> That pop-up must mean that something actually did go wrong, so I guess it can't be ignored. I'll reopen this. Unfortunately, I don't have any flights to test with right now.
> 
> @bradzab0623 does the same thing happen when you use a reservation instead of an account?

Interesting the first attempt worked but ~4 subsequent attempts failed.
```
 docker run jdholtz/auto-southwest-check-in:develop <num> Jessica Zabinski --verbose
2024-02-16 20:41:38 DEBUG MainProcess[log:23]: Initialized the application
2024-02-16 20:41:38 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.2
2024-02-16 20:41:38 DEBUG MainProcess[main:113]: Called with 3 arguments
2024-02-16 20:41:38 DEBUG MainProcess[config:120]: Initializing configuration file
2024-02-16 20:41:38 DEBUG MainProcess[config:149]: Reading the configuration file
2024-02-16 20:41:38 DEBUG MainProcess[config:153]: No configuration file found. Using defaults
2024-02-16 20:41:38 DEBUG MainProcess[config:163]: Reading configuration from environment variables
2024-02-16 20:41:38 DEBUG MainProcess[config:139]: Creating configurations for 1 reservations
2024-02-16 20:41:38 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2024-02-16 20:41:38 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2024-02-16 20:41:38 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2024-02-16 20:41:38 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2024-02-16 20:41:38 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2024-02-16 20:41:38 DEBUG Process-1[webdriver:106]: Starting webdriver for current session
2024-02-16 20:41:39 DEBUG Process-1[webdriver:122]: Using browser version: 121.0.6167.184
2024-02-16 20:41:39 DEBUG Process-1[webdriver:126]: Loading Southwest Check-In page
2024-02-16 20:41:42 DEBUG Process-1[webdriver:64]: Waiting for valid headers
2024-02-16 20:41:42 DEBUG Process-1[webdriver:155]: Waiting for headers_set to be set
2024-02-16 20:41:43 DEBUG Process-1[webdriver:159]: headers_set set successfully
2024-02-16 20:41:43 DEBUG Process-1[reservation_monitor:84]: Scheduling flight check-ins for 1 reservations
2024-02-16 20:41:43 DEBUG Process-1[checkin_scheduler:76]: Retrieving reservation information
2024-02-16 20:41:58 DEBUG Process-1[utils:39]: Failed to make request after 20 attempts: Forbidden 403
2024-02-16 20:41:58 DEBUG Process-1[utils:42]: Response body: {
  "code": 403050700
}
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:82]: Failed to retrieve reservation info. Error: Forbidden 403. Exiting
2024-02-16 20:41:58 DEBUG Process-1[notification_handler:76]: Sending failed reservation retrieval notification...
Failed to retrieve reservation for Jessica Zabinski with confirmation number <num>. Reason: Forbidden 403.
Make sure the reservation information is correct and try again.

2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:57]: 0 flights found under current reservation
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:43]: 0 total flights were found
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:100]: 0 new flights found
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:104]: Scheduling 0 flights for check-in
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:116]: 0 flights are currently scheduled. Removing old flights
2024-02-16 20:41:58 DEBUG Process-1[checkin_scheduler:132]: Successfully removed old flights. 0 flights are now scheduled
2024-02-16 20:41:58 DEBUG Process-1[reservation_monitor:71]: No more flights are scheduled for check-in. Exiting...
```

**Comment by dmytrokoren** [comment] 2024-02-21 03:53
@jdholtz 403 issue for me is resolved. I was able to login to account and successfully retrieve the reservation.

<img width="1357" alt="image" src="https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/9ffac8fd-3935-4001-89b9-b233590b404a">

**Comment by rcallison** [comment] 2024-02-22 05:13
I am seeing the 403 error on the develop branch now.
It logs me in and pulls my reservation, but then fails.

Failed to retrieve reservation for <First> <Last> with confirmation number <confirm>. Reason: Forbidden 403.
Make sure the reservation information is correct and try again.

**Comment by jdholtz** [comment] 2024-02-26 16:57
I'll close this issue in favor of #230, where the 403 error will be tracked (which is the underlying cause of this issue).

**Closed by jdholtz** 2024-02-26 16:57 UTC
Labels: bug
