### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable (_check_for_companion)

### ISSUE THREAD

**Issue by rufus210** [jdholtz/auto-southwest-check-in#191] opened 2023-12-08 01:31 UTC
### Version

Auto-Southwest Check-In v7.1

### Browser Version

Chrome 109.0.5414.74

### Description

Successfully scheduled the following flights to check in for XX XX:
Flight from XYZ to ABC at 2023-12-10 21:00:00 UTC

Unexpected error during fare check: TypeError("argument of type 'NoneType' is not iterable")
Traceback (most recent call last):
  File "/home/rufus/auto-southwest-check-in/lib/reservation_monitor.py", line 100, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 31, in check_flight_price
    flight_price = self._get_flight_price(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 49, in _get_flight_price
    flights, fare_type = self._get_matching_flights(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 68, in _get_matching_flights
    change_flight_page, fare_type_bounds = self._get_change_flight_page(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 100, in _get_change_flight_page
    self._check_for_companion(reservation_info)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 144, in _check_for_companion
    and "companion" in grey_box_message["body"]
TypeError: argument of type 'NoneType' is not iterable

### To Reproduce

Run the script

### Expected Behavior

No error

### Relevant logs and program output

```sh
2023-12-07 17:25:04 DEBUG MainProcess[log:23]: Initialized the application
2023-12-07 17:25:04 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.1
2023-12-07 17:25:04 DEBUG MainProcess[main:113]: Called with 3 arguments
2023-12-07 17:25:05 DEBUG MainProcess[config:107]: Initializing configuration file
2023-12-07 17:25:05 DEBUG MainProcess[config:135]: Reading the configuration file
2023-12-07 17:25:05 DEBUG MainProcess[config:53]: Setting check fares to True
2023-12-07 17:25:05 DEBUG MainProcess[config:67]: Setting notification level to <NotificationLevel.INFO: 1>
2023-12-07 17:25:05 DEBUG MainProcess[config:80]: Using 1 notification services
2023-12-07 17:25:05 DEBUG MainProcess[config:84]: Setting retrieval interval to 24 hours
2023-12-07 17:25:05 DEBUG MainProcess[config:118]: Creating configurations for 0 accounts
2023-12-07 17:25:05 DEBUG MainProcess[config:125]: Creating configurations for 0 reservations
2023-12-07 17:25:05 DEBUG MainProcess[config:125]: Creating configurations for 1 reservations
2023-12-07 17:25:05 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2023-12-07 17:25:05 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2023-12-07 17:25:05 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2023-12-07 17:25:05 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2023-12-07 17:25:05 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2023-12-07 17:25:05 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2023-12-07 17:25:06 DEBUG Process-1[webdriver:119]: Using browser version: 109.0.5414.119
2023-12-07 17:25:06 DEBUG Process-1[webdriver:123]: Loading Southwest Check-In page
2023-12-07 17:25:11 DEBUG Process-1[webdriver:65]: Waiting for valid headers
2023-12-07 17:25:11 DEBUG Process-1[webdriver:152]: Waiting for headers_set to be set
2023-12-07 17:25:12 DEBUG Process-1[webdriver:156]: headers_set set successfully
2023-12-07 17:25:12 DEBUG Process-1[reservation_monitor:84]: Scheduling flight check-ins for 1 reservations
2023-12-07 17:25:12 DEBUG Process-1[checkin_scheduler:76]: Retrieving reservation information
2023-12-07 17:25:16 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:89]: Successfully retrieved reservation information
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:57]: 2 flights found under current reservation
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:43]: 1 total flights were found
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:100]: 1 new flights found
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:104]: Scheduling 1 flights for check-in
2023-12-07 17:25:16 DEBUG Process-1[checkin_handler:41]: Scheduling check-in for current flight
2023-12-07 17:25:16 DEBUG Process-1[notification_handler:66]: Sending new flights notification
2023-12-07 17:25:16 DEBUG Process-1:1[checkin_handler:89]: Sleeping until thirty minutes before check-in...
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:116]: 1 flights are currently scheduled. Removing old flights
2023-12-07 17:25:16 DEBUG Process-1[checkin_scheduler:132]: Successfully removed old flights. 1 flights are now scheduled
2023-12-07 17:25:16 DEBUG Process-1[reservation_monitor:93]: Checking fares for 1 flights
2023-12-07 17:25:16 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2023-12-07 17:25:16 DEBUG Process-1[fare_checker:88]: Fetching reservation information
2023-12-07 17:25:20 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-07 17:25:20 ERROR Process-1[reservation_monitor:106]: Unexpected error during fare check: TypeError("argument of type 'NoneType' is not iterable")
Traceback (most recent call last):
  File "/home/rufus/auto-southwest-check-in/lib/reservation_monitor.py", line 100, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 31, in check_flight_price
    flight_price = self._get_flight_price(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 49, in _get_flight_price
    flights, fare_type = self._get_matching_flights(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 68, in _get_matching_flights
    change_flight_page, fare_type_bounds = self._get_change_flight_page(flight)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 100, in _get_change_flight_page
    self._check_for_companion(reservation_info)
  File "/home/rufus/auto-southwest-check-in/lib/fare_checker.py", line 144, in _check_for_companion
    and "companion" in grey_box_message["body"]
TypeError: argument of type 'NoneType' is not iterable
2023-12-07 17:25:20 DEBUG Process-1[reservation_monitor:80]: Lock released
2023-12-07 17:25:20 DEBUG Process-1[reservation_monitor:116]: Sleeping for 86384 seconds
2023-12-07 17:25:33 INFO MainProcess[main:167]: 
Ctrl+C pressed. Stopping all check-ins
2023-12-07 17:25:33 DEBUG Process-1[checkin_handler:52]: Stopping check-in for current flight
2023-12-07 17:25:33 DEBUG Process-1[checkin_handler:55]: Killing process with PID 1085882
2023-12-07 17:25:33 DEBUG Process-1[checkin_handler:59]: Waiting for process with PID 1085882 to be terminated
2023-12-07 17:25:33 DEBUG Process-1[checkin_handler:65]: Process with PID 1085882 successfully terminated
```

### Additional context

My guess is the issue is checking fare for a flight where the 1st leg has already been checked in is causing confusing.

**Comment by jdholtz** [comment] 2023-12-08 03:02
Thanks for reporting this. I was able to reproduce it in a test case and it has since been fixed on the develop branch. 

> Strange - I just ran the script again and this time there was no error.

Interesting. The Southwest API can be a little finicky on what it returns, so it may be a rare occurrence to see this issue. Anyways, it is handled correctly now.

**Closed by jdholtz** 2023-12-08 03:02 UTC
Labels: bug
