### ISSUE TITLE
Timing out on starting webdriver

### ISSUE THREAD

**Issue by cmclinton** [jdholtz/auto-southwest-check-in#176] opened 2023-10-18 12:51 UTC
### Version

6.1

### Description

Python is crashing with unknown error: cannot connect to chrome at 127.0.0.1:9222 from chrome not reachable.

Note - I'm on WSL and just upgraded to Chrome 118

### To Reproduce

python3 southwest.py username password

### Relevant logs and program output

```sh
2023-10-18 08:46:37 DEBUG MainProcess[log:23]: Initialized the application
2023-10-18 08:46:37 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-18 08:46:37 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-10-18 08:46:37 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-18 08:46:37 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-18 08:46:37 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-18 08:46:37 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-18 08:46:37 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-10-18 08:46:37 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-18 08:46:37 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-18 08:46:37 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-18 08:46:37 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-18 08:46:37 DEBUG Process-1[webdriver:124]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 126, in _get_driver
    driver = Driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 307, in __init__
    super().__init__(options=options, service=service_)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 433, in start_session
    super().start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable
Stacktrace:
#0 0x55fdf7965fb3 <unknown>
#1 0x55fdf76392f6 <unknown>
#2 0x55fdf7624ffa <unknown>
#3 0x55fdf7670a3c <unknown>
#4 0x55fdf76682a9 <unknown>
#5 0x55fdf76abac6 <unknown>
#6 0x55fdf76a2713 <unknown>
#7 0x55fdf767518b <unknown>
#8 0x55fdf7675f7e <unknown>
#9 0x55fdf792b8d8 <unknown>
#10 0x55fdf792f800 <unknown>
#11 0x55fdf7939cfc <unknown>
#12 0x55fdf7930418 <unknown>
#13 0x55fdf78fd42f <unknown>
#14 0x55fdf79544e8 <unknown>
#15 0x55fdf79546b4 <unknown>
#16 0x55fdf7965143 <unknown>
#17 0x7fdf5fbeeac3 <unknown>
```

### Additional context

Google Chrome 118.0.5993.88

**Comment by jdholtz** [comment] 2023-10-18 15:49
Could you try the latest develop commit? It may be an issue with different versions between Chrome and Chromedriver which was fixed in #172.

**Comment by cmclinton** [comment] 2023-10-18 23:56
I switched to the develop branch, reran pip requirements, and got the exact same error.

```
2023-10-18 19:52:33 DEBUG MainProcess[log:23]: Initialized the application
2023-10-18 19:52:33 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-18 19:52:33 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-10-18 19:52:33 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-18 19:52:33 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-18 19:52:33 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-18 19:52:33 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-18 19:52:33 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-10-18 19:52:33 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-18 19:52:33 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-18 19:52:33 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-18 19:52:33 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-18 19:52:33 DEBUG Process-1[webdriver:102]: Starting webdriver for current session

Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 118.0.5993.88 (Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.88/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/drivers/uc_driver

Making [uc_driver 118.0.5993.88] executable ...
[uc_driver 118.0.5993.88] is now ready for use!

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 104, in _get_driver
    driver = Driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 427, in Driver
    driver = browser_launcher.get_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1485, in get_driver
    return get_local_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3274, in get_local_driver
    driver = undetected.Chrome(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 305, in __init__
    super().__init__(options=options, service=service_)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 430, in start_session
    super().start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable
Stacktrace:
#0 0x555845890f73 <unknown>
#1 0x5558455642f6 <unknown>
#2 0x55584554fffa <unknown>
#3 0x55584559ba3c <unknown>
#4 0x5558455932a9 <unknown>
#5 0x5558455d6ac6 <unknown>
#6 0x5558455cd713 <unknown>
#7 0x5558455a018b <unknown>
#8 0x5558455a0f7e <unknown>
#9 0x555845856898 <unknown>
#10 0x55584585a7c0 <unknown>
#11 0x555845864cbc <unknown>
#12 0x55584585b3d8 <unknown>
#13 0x5558458283ef <unknown>
#14 0x55584587f4a8 <unknown>
#15 0x55584587f674 <unknown>
#16 0x555845890103 <unknown>
#17 0x7f0da08d8ac3 <unknown>
```

**Comment by cmclinton** [comment] 2023-10-18 23:59
I also tried just using reservation number and firstname lastname. Same error.

**Comment by jdholtz** [comment] 2023-10-19 15:57
> just upgraded to Chrome 118

Did it work with previous Chrome versions?

**Comment by jmselk** [comment] 2023-10-19 16:19
Same error here using docker on OSX with an M1

```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 117.0.5938.149 (Previous Version)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver

Making [uc_driver 117.0.5938.149] executable ...
[uc_driver 117.0.5938.149] is now ready for use!

Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/app/lib/reservation_monitor.py", line 65, in _monitor
    self.checkin_scheduler.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 63, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 126, in _get_driver
    driver = Driver(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 307, in __init__
    super().__init__(options=options, service=service_)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver unexpectedly exited. Status code was: 255
```

**Comment by jmselk** [comment] 2023-10-19 16:50
@jdholtz Sorry for not looking that closely... Want me to open a separate issue?

**Comment by jdholtz** [comment] 2023-10-19 17:37
> Want me to open a separate issue?

Yeah, that’d be great

**Comment by jdholtz** [comment] 2023-10-25 00:10
@cmclinton do you have any updates from my comment [here](https://github.com/jdholtz/auto-southwest-check-in/issues/176#issuecomment-1771282396)?

**Comment by cmclinton** [comment] 2023-10-25 00:41
I ran ```sudo apt install xvfb``` and then ran southwest.py

```
2023-10-24 20:37:13 DEBUG MainProcess[log:23]: Initialized the application
2023-10-24 20:37:13 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-24 20:37:13 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-10-24 20:37:13 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-24 20:37:13 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-24 20:37:13 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-24 20:37:13 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-24 20:37:13 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-10-24 20:37:13 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-24 20:37:13 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-24 20:37:13 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-24 20:37:13 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-24 20:37:13 DEBUG Process-1[webdriver:124]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 126, in _get_driver
    driver = Driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 307, in __init__
    super().__init__(options=options, service=service_)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 433, in start_session
    super().start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute    self.error_handler.check_response(response)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable
Stacktrace:
#0 0x55fc3f00bf73 <unknown>
#1 0x55fc3ecdf2f6 <unknown>
#2 0x55fc3eccaffa <unknown>
#3 0x55fc3ed16a3c <unknown>
#4 0x55fc3ed0e2a9 <unknown>
#5 0x55fc3ed51ac6 <unknown>
#6 0x55fc3ed48713 <unknown>
#7 0x55fc3ed1b18b <unknown>
#8 0x55fc3ed1bf7e <unknown>
#9 0x55fc3efd1898 <unknown>
#10 0x55fc3efd57c0 <unknown>
#11 0x55fc3efdfcbc <unknown>
#12 0x55fc3efd63d8 <unknown>
#13 0x55fc3efa33ef <unknown>
#14 0x55fc3effa4a8 <unknown>
#15 0x55fc3effa674 <unknown>
#16 0x55fc3f00b103 <unknown>
#17 0x7f6f1f256ac3 <unknown>```

Google Chrome 118.0.5993.117

**Comment by cmclinton** [comment] 2023-10-25 00:45
I then switched to the develop branch and re-ran pip requirements. I then got....

```
2023-10-24 20:44:21 DEBUG MainProcess[log:23]: Initialized the application
2023-10-24 20:44:21 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-24 20:44:21 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-10-24 20:44:21 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-24 20:44:21 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-24 20:44:21 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-24 20:44:21 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-10-24 20:44:21 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-10-24 20:44:21 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-10-24 20:44:21 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-10-24 20:44:21 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-10-24 20:44:21 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-10-24 20:44:21 DEBUG Process-1[webdriver:102]: Starting webdriver for current session

Warning: uc_driver update needed. Getting it now:
2023-10-24 20:44:24 DEBUG Process-1[webdriver:111]: Using browser version: 118.0.5993.70
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 113, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
```

**Comment by jdholtz** [comment] 2023-10-25 01:23
Is this the same issue as https://github.com/jdholtz/auto-southwest-check-in/issues/169?

**Comment by cmclinton** [comment] 2023-10-25 01:31
No. The SSL error was only at work presumably due to network settings.

**Comment by jdholtz** [comment] 2023-10-29 03:33
If you do `sbase get chromedriver` or `sbase get uc_driver` through the command line, do you get any errors. It’s probably not downloading the driver correctly.

**Comment by jdholtz** [comment] 2023-11-04 01:17
@cmclinton have you been able to try my above suggestions about downloading the driver manually?

**Comment by cmclinton** [comment] 2023-11-08 02:21
```
sbase get chromedriver

*** chromedriver to download = 119.0.6045.105 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip ...
Unzip Complete!

The file [chromedriver] was saved to:
/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/drivers/chromedriver

Making [chromedriver 119.0.6045.105] executable ...
[chromedriver 119.0.6045.105] is now ready for use!
```
```
 sbase get uc_driver

*** chromedriver to download = 119.0.6045.105 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/drivers/uc_driver

Making [uc_driver 119.0.6045.105] executable ...
[uc_driver 119.0.6045.105] is now ready for use!
```
I then downloaded and installed google-chrome 119.0.6045.105 and installed auto-southwest-check-in 7.0 fresh. I then ran pip install -r requirements.txt and launched python3 southwest.py USERNAME PASSWORD

``` 
python3 southwest.py [myusername] [mypassword]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 104, in _get_driver
    driver = Driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 453, in Driver
    driver = browser_launcher.get_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1524, in get_driver
    return get_local_driver(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3342, in get_local_driver
    driver = undetected.Chrome(
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 305, in __init__
    super().__init__(options=options, service=service_)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 430, in start_session
    super().start_session(capabilities)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/cclinton/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from chrome not reachable
Stacktrace:
#0 0x55d9e2b725e3 <unknown>
#1 0x55d9e2834f0d <unknown>
#2 0x55d9e281f50a <unknown>
#3 0x55d9e2870cfd <unknown>
#4 0x55d9e2867abf <unknown>
#5 0x55d9e28b347f <unknown>
#6 0x55d9e28a9cc3 <unknown>
#7 0x55d9e28750e4 <unknown>
#8 0x55d9e28760ae <unknown>
#9 0x55d9e2b38ce1 <unknown>
#10 0x55d9e2b3cb7e <unknown>
#11 0x55d9e2b264b5 <unknown>
#12 0x55d9e2b3d7d6 <unknown>
#13 0x55d9e2b09dbf <unknown>
#14 0x55d9e2b60748 <unknown>
#15 0x55d9e2b60917 <unknown>
#16 0x55d9e2b71773 <unknown>
#17 0x7fe74f9feac3 <unknown>
```
I just tried the docker version and that seemed to work on my system. I may just go docker.

**Comment by jdholtz** [comment] 2023-11-08 19:23
> I just tried the docker version and that seemed to work on my system. I may just go docker.

I'm glad that the Docker image works for you.

If you want, would you be able to try a few commands in the `python` terminal to narrow down the issue?
First, try this and you should still get the error:
```python
>>> from seleniumbase import Driver
>>> driver = Driver(headless=True, undetectable=True, uc_cdp_events=True)
```

If you do get the error, can you try this in the `python` terminal and see if the issue is still present? Using a context manager like this handles the issue you are getting better.
```python
>>> from seleniumbase import SB
>>> with SB(undetectable=True, headless=True, uc_cdp_events=True) as sb:
...     sb.driver.get("https://mobile.southwest.com/check-in")
...
```

**Comment by cmclinton** [comment] 2023-11-10 23:16
I tried both and got the exact same error as above, i.e. cannot connect to chrome....and a stacktrace with the same hex values.

**Comment by jdholtz** [comment] 2023-11-10 23:58
> I tried both and got the exact same error as above, i.e. cannot connect to chrome....and a stacktrace with the same hex values

In that case, since it is not a direct issue with this script, you can file an issue on the SeleniumBase repository by showing the issue using the first block of code (the one without the `with` context manager) and just having SeleniumBase installed (not the other dependencies of the script).

**Comment by jdholtz** [comment] 2023-11-19 13:02
@cmclinton because the issue is reproducible without using this script on your end and no one else has reported having the same issue with this script (at least, in this issue), I’m going to close this. 

For further steps, I recommend to file an issue upstream in the SeleniumBase repository, per my comment above.

**Closed by jdholtz** 2023-11-19 13:02 UTC
Labels: dependency
