### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mrvizine** [jdholtz/auto-southwest-check-in#229] opened 2024-02-25 00:38 UTC
### Version

7.2

### Browser Version

not sure what version or browser it's trying to use as it does not get there

### Description

(myenv) PS C:\Users\brian\Documents\auto-southwest-check-in> python3 southwest.py USERNAME PASSWORD
Traceback (most recent call last):
  File "C:\Users\brian\Documents\auto-southwest-check-in\southwest.py", line 10, in <module>
    main(arguments)
  File "C:\Users\brian\Documents\auto-southwest-check-in\lib\main.py", line 165, in main
    set_up_check_in(arguments)
  File "C:\Users\brian\Documents\auto-southwest-check-in\lib\main.py", line 118, in set_up_check_in
    from .config import GlobalConfig
  File "C:\Users\brian\Documents\auto-southwest-check-in\lib\config.py", line 8, in <module>
    from .utils import NotificationLevel, is_truthy
  File "C:\Users\brian\Documents\auto-southwest-check-in\lib\utils.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### To Reproduce

python3 southwest.py USERNAME PASSWORD
or
python3 southwest.py CONFIRMATION_NUMBER FIRST_NAME LAST_NAME

**Comment by jdholtz** [comment] 2024-02-25 01:32
Have you installed the dependencies with `pip install -r requirements.txt` in your environment? If so, can you send the output of `pip freeze`?

**Comment by mrvizine** [comment] 2024-02-25 01:43
Yes I did do that. Asked to upgrade pip which I did and did a force reinstall on requirements. What would be the pip freeze? I stepped away but once home can send further outputs. Thank you

**Comment by jdholtz** [comment] 2024-02-26 14:24
The pip freeze output shows the module, so it definitely is being installed. It’s possible that you have multiple versions of Python installed and `pip` is installing it for a different version than what `python3` is using. 

If you rerun the Pip command in your virtual environment using `pip3` instead of `pip`, does that install the packages in the correct place? If not, can you send the output of the pip install logs (removing any names in the directories if necessary)

**Comment by kevingrubbs** [comment] 2024-02-26 15:01
Sorry, not intending to hijack @mrvizine's post here, but hoping that we are actually having the same issue and can help solve it :) 

I wasn't running under virtualenv before, so I am now doing that. I ran the install requirements with pip and everything installed (seemed to be from cache)... I ran again with `pip3 install --force-reinstall --no-cache-dir --require-virtualenv -r requirements.txt` and am attaching the [force install no-cache logs](https://github.com/jdholtz/auto-southwest-check-in/files/14406300/pip-force-reinstall.txt) from that command and also just the [normal install command that confirms the paths](https://github.com/jdholtz/auto-southwest-check-in/files/14406336/install_confirmation.txt)... however I'm getting a different error now when trying to run the script.

> (swcheckin) <user>@Kevins-MBP-M2 auto-southwest-check-in % python3 southwest.py --verbose                                                                                              
> 2024-02-26 08:58:31 DEBUG MainProcess[log:23]: Initialized the application
> 2024-02-26 08:58:31 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.2
> 2024-02-26 08:58:31 DEBUG MainProcess[main:113]: Called with 0 arguments
> 2024-02-26 08:58:31 DEBUG MainProcess[config:108]: Initializing configuration file
> 2024-02-26 08:58:31 DEBUG MainProcess[config:137]: Reading the configuration file
> 2024-02-26 08:58:31 DEBUG MainProcess[config:151]: Reading configuration from environment variables
> 2024-02-26 08:58:31 DEBUG MainProcess[config:54]: Setting check fares to True
> 2024-02-26 08:58:31 DEBUG MainProcess[config:68]: Setting notification level to <NotificationLevel.INFO: 1>
> 2024-02-26 08:58:31 DEBUG MainProcess[config:81]: Using 0 notification services
> 2024-02-26 08:58:31 DEBUG MainProcess[config:85]: Setting retrieval interval to 24 hours
> 2024-02-26 08:58:31 DEBUG MainProcess[config:120]: Creating configurations for 0 accounts
> 2024-02-26 08:58:31 DEBUG MainProcess[config:127]: Creating configurations for 2 reservations
> 2024-02-26 08:58:31 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 2 reservations
> 2024-02-26 08:58:31 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
> 2024-02-26 08:58:31 DEBUG Process-1[reservation_monitor:62]: Lock acquired
> 2024-02-26 08:58:31 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
> 2024-02-26 08:58:31 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
> 2024-02-26 08:58:31 DEBUG Process-2[reservation_monitor:60]: Acquiring lock...
> 
> Warning: uc_driver not found. Getting it now:
> 
> *** chromedriver to download = 122.0.6261.69 (Latest Stable) 
> 
> Downloading chromedriver-mac-x64.zip from:
> https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.69/mac-x64/chromedriver-mac-x64.zip ...
> Download Complete!
> 
> 2024-02-26 08:58:33 DEBUG Process-1[webdriver:119]: Using browser version: 122.0.6261.69
> Process Process-1:
> 2024-02-26 08:58:33 DEBUG Process-2[reservation_monitor:62]: Lock acquired
> 2024-02-26 08:58:33 DEBUG Process-2[checkin_scheduler:50]: Refreshing headers for current session
> 2024-02-26 08:58:33 DEBUG Process-2[webdriver:103]: Starting webdriver for current session
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/<user>/Documents/_scripts/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
>     self._monitor()
>   File "/Users/<user>/Documents/_scripts/auto-southwest-check-in/lib/reservation_monitor.py", line 65, in _monitor
>     self.checkin_scheduler.refresh_headers()
>   File "/Users/<user>/Documents/_scripts/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
>     webdriver.set_headers()
>   File "/Users/<user>/Documents/_scripts/auto-southwest-check-in/lib/webdriver.py", line 64, in set_headers
>     driver = self._get_driver()
>              ^^^^^^^^^^^^^^^^^^
>   File "/Users/<user>/Documents/_scripts/auto-southwest-check-in/lib/webdriver.py", line 121, in _get_driver
>     driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
>     ^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'

After the above, it tries again to download the uc_driver and outputs basically the same thing again.
I'm not sure if something about homebrew install is conflicting, based on those paths above? Sorry I'm not a python environment guru, so thanks in advance for the help!

**Comment by kevingrubbs** [comment] 2024-02-26 16:57
> SeleniumBase seems to not be downloading the driver correctly. Does running sbase get uc_driver and re-running the script work?

Looks like this is a piece that is failing... it attempts 3 times and gives up.

> (swcheckin) <user>@Kevins-MBP-M2 auto-southwest-check-in % sbase get uc_driver
> 
> *** chromedriver to download = 122.0.6261.69 (Latest Stable) 
> 
> Downloading chromedriver-mac-x64.zip from:
> https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.69/mac-x64/chromedriver-mac-x64.zip ...
> Download Complete!
> 
> 
> * Unable to download driver! Retrying in 3s...

the zip file gives 404 when you [hit it directly](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.69/mac-x64/chromedriver-mac-x64.zip).

**Comment by jdholtz** [comment] 2024-02-26 17:08
> Any idea when this will be on the master branch again?

Hopefully by the end of this week. I want to add another small feature before making the next release.

**Comment by mrvizine** [comment] 2024-02-26 18:53
after i do that pip3 command no cache require virtual etc. it installs stuff but then gives me a red output: ERROR: To modify pip, please run the following command:
C:\Users\brian\auto-southwest-check-in\myenv\Scripts\python.exe -m pip install --force-reinstall --no-cache-dir --require-virtualenv -r requirements.txt

**Comment by mrvizine** [comment] 2024-02-26 19:12
Full breakdown: 

C:\Users\brian\auto-southwest-check-in>git pull && git checkout develop
Already up to date.
Already on 'develop'
Your branch is up to date with 'origin/develop'.

C:\Users\brian\auto-southwest-check-in>python -m venv myenv

C:\Users\brian\auto-southwest-check-in>myenv\Scripts\activate

(myenv) C:\Users\brian\auto-southwest-check-in>pip3 install --force-reinstall --no-cache-dir --require-virtualenv -r requirements.txt
Collecting apprise==1.7.2 (from -r requirements.txt (line 1))
  Downloading apprise-1.7.2-py3-none-any.whl.metadata (43 kB)
     ---------------------------------------- 43.8/43.8 kB 2.1 MB/s eta 0:00:00
Collecting pytz==2024.1 (from -r requirements.txt (line 2))
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting requests==2.31.0 (from -r requirements.txt (line 3))
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting seleniumbase==4.23.4 (from -r requirements.txt (line 4))
  Downloading seleniumbase-4.23.4-py3-none-any.whl.metadata (83 kB)
     ---------------------------------------- 83.8/83.8 kB ? eta 0:00:00
Collecting certifi (from apprise==1.7.2->-r requirements.txt (line 1))
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting requests-oauthlib (from apprise==1.7.2->-r requirements.txt (line 1))
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting click>=5.0 (from apprise==1.7.2->-r requirements.txt (line 1))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting markdown (from apprise==1.7.2->-r requirements.txt (line 1))
  Downloading Markdown-3.5.2-py3-none-any.whl.metadata (7.0 kB)
Collecting PyYAML (from apprise==1.7.2->-r requirements.txt (line 1))
  Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.31.0->-r requirements.txt (line 3))
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests==2.31.0->-r requirements.txt (line 3))
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.31.0->-r requirements.txt (line 3))
  Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting pip>=24.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Collecting packaging>=23.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting wheel>=0.42.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Collecting attrs>=23.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting parse>=1.20.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading parse-1.20.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting parse-type>=0.6.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading parse_type-0.6.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting six==1.16.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting chardet==5.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting pynose==1.4.8 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pynose-1.4.8-py3-none-any.whl.metadata (18 kB)
Collecting sniffio==1.3.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading sniffio-1.3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting h11==0.14.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting outcome==1.3.0.post0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting trio-websocket==0.11.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Collecting wsproto==1.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting cssselect==1.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting sortedcontainers==2.4.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting fasteners==0.19 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading fasteners-0.19-py3-none-any.whl.metadata (4.9 kB)
Collecting execnet==2.0.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading execnet-2.0.2-py3-none-any.whl.metadata (2.9 kB)
Collecting iniconfig==2.0.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting py==1.11.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading py-1.11.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting pytest-html==2.0.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest_html-2.0.1-py2.py3-none-any.whl (15 kB)
Collecting pytest-ordering==0.6 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest_ordering-0.6-py3-none-any.whl (4.6 kB)
Collecting pytest-rerunfailures==13.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest_rerunfailures-13.0-py3-none-any.whl.metadata (18 kB)
Collecting pytest-xdist==3.5.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest_xdist-3.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting parameterized==0.9.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting sbvirtualdisplay==1.3.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading sbvirtualdisplay-1.3.0-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting behave==1.2.6 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading behave-1.2.6-py2.py3-none-any.whl (136 kB)
     ---------------------------------------- 136.8/136.8 kB ? eta 0:00:00
Collecting beautifulsoup4==4.12.3 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pygments==2.17.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting tabcompleter==1.3.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading tabcompleter-1.3.0-py3-none-any.whl.metadata (3.5 kB)
Collecting pdbp==1.5.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pdbp-1.5.0-py3-none-any.whl.metadata (7.1 kB)
Collecting colorama==0.4.6 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting exceptiongroup==1.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)
Collecting pyotp==2.9.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pyotp-2.9.0-py3-none-any.whl.metadata (9.8 kB)
Collecting mdurl==0.1.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting rich==13.7.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting pyreadline3==3.4.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pyreadline3-3.4.1-py3-none-any.whl.metadata (2.0 kB)
Collecting setuptools>=69.1.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading setuptools-69.1.1-py3-none-any.whl.metadata (6.2 kB)
Collecting filelock>=3.13.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting platformdirs>=4.2.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading platformdirs-4.2.0-py3-none-any.whl.metadata (11 kB)
Collecting typing-extensions>=4.9.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
Collecting trio==0.24.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading trio-0.24.0-py3-none-any.whl.metadata (4.9 kB)
Collecting selenium==4.17.2 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading selenium-4.17.2-py3-none-any.whl.metadata (6.9 kB)
Collecting pluggy==1.4.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pluggy-1.4.0-py3-none-any.whl.metadata (4.3 kB)
Collecting pytest==8.0.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest-8.0.0-py3-none-any.whl.metadata (7.8 kB)
Collecting pytest-metadata==3.1.1 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pytest_metadata-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Collecting soupsieve==2.5 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting markdown-it-py==3.0.0 (from seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting cffi>=1.14 (from trio==0.24.0->seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading cffi-1.16.0-cp311-cp311-win_amd64.whl.metadata (1.5 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib->apprise==1.7.2->-r requirements.txt (line 1))
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Collecting pycparser (from cffi>=1.14->trio==0.24.0->seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium==4.17.2->seleniumbase==4.23.4->-r requirements.txt (line 4))
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading apprise-1.7.2-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 25.8 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ---------------------------------------- 505.5/505.5 kB ? eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 62.6/62.6 kB ? eta 0:00:00
Downloading seleniumbase-4.23.4-py3-none-any.whl (551 kB)
   ---------------------------------------- 551.3/551.3 kB 33.8 MB/s eta 0:00:00
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ---------------------------------------- 147.9/147.9 kB ? eta 0:00:00
Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
   ---------------------------------------- 199.4/199.4 kB ? eta 0:00:00
Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
   ---------------------------------------- 99.9/99.9 kB 6.0 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Downloading execnet-2.0.2-py3-none-any.whl (37 kB)
Downloading fasteners-0.19-py3-none-any.whl (18 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
   ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ---------------------------------------- 61.6/61.6 kB ? eta 0:00:00
Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ---------------------------------------- 87.5/87.5 kB ? eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Downloading pdbp-1.5.0-py3-none-any.whl (17 kB)
Downloading pluggy-1.4.0-py3-none-any.whl (20 kB)
Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
   ---------------------------------------- 98.7/98.7 kB ? eta 0:00:00
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 36.5 MB/s eta 0:00:00
Downloading pynose-1.4.8-py3-none-any.whl (116 kB)
   ---------------------------------------- 116.0/116.0 kB ? eta 0:00:00
Downloading pyotp-2.9.0-py3-none-any.whl (13 kB)
Downloading pyreadline3-3.4.1-py3-none-any.whl (95 kB)
   ---------------------------------------- 95.2/95.2 kB ? eta 0:00:00
Downloading pytest-8.0.0-py3-none-any.whl (334 kB)
   ---------------------------------------- 334.0/334.0 kB ? eta 0:00:00
Downloading pytest_metadata-3.1.1-py3-none-any.whl (11 kB)
Downloading pytest_rerunfailures-13.0-py3-none-any.whl (12 kB)
Downloading pytest_xdist-3.5.0-py3-none-any.whl (42 kB)
   ---------------------------------------- 42.0/42.0 kB ? eta 0:00:00
Downloading rich-13.7.0-py3-none-any.whl (240 kB)
   ---------------------------------------- 240.6/240.6 kB ? eta 0:00:00
Downloading sbvirtualdisplay-1.3.0-py2.py3-none-any.whl (12 kB)
Downloading selenium-4.17.2-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 9.9/9.9 MB 30.1 MB/s eta 0:00:00
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading tabcompleter-1.3.0-py3-none-any.whl (6.5 kB)
Downloading trio-0.24.0-py3-none-any.whl (460 kB)
   ---------------------------------------- 460.2/460.2 kB 28.1 MB/s eta 0:00:00
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
   ---------------------------------------- 60.8/60.8 kB ? eta 0:00:00
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ---------------------------------------- 163.8/163.8 kB ? eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ---------------------------------------- 97.9/97.9 kB ? eta 0:00:00
Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ---------------------------------------- 53.0/53.0 kB ? eta 0:00:00
Downloading parse-1.20.1-py2.py3-none-any.whl (20 kB)
Downloading parse_type-0.6.2-py2.py3-none-any.whl (26 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 2.1/2.1 MB 26.9 MB/s eta 0:00:00
Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
   ---------------------------------------- 144.7/144.7 kB ? eta 0:00:00
Downloading setuptools-69.1.1-py3-none-any.whl (819 kB)
   ---------------------------------------- 819.3/819.3 kB 26.1 MB/s eta 0:00:00
Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ---------------------------------------- 121.1/121.1 kB ? eta 0:00:00
Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
   ---------------------------------------- 65.4/65.4 kB ? eta 0:00:00
Downloading Markdown-3.5.2-py3-none-any.whl (103 kB)
   ---------------------------------------- 103.9/103.9 kB ? eta 0:00:00
Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Downloading cffi-1.16.0-cp311-cp311-win_amd64.whl (181 kB)
   ---------------------------------------- 181.5/181.5 kB ? eta 0:00:00
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
   ---------------------------------------- 151.7/151.7 kB ? eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ---------------------------------------- 118.7/118.7 kB ? eta 0:00:00
ERROR: To modify pip, please run the following command:
C:\Users\brian\auto-southwest-check-in\myenv\Scripts\python.exe -m pip install --force-reinstall --no-cache-dir --require-virtualenv -r requirements.txt

(myenv) C:\Users\brian\auto-southwest-check-in>python southwest.py

(myenv) C:\Users\brian\auto-southwest-check-in>python southwest.py USERNAME PASSWORD

*** chromedriver to download = 122.0.6261.69 (Latest Stable)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.69/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [chromedriver.exe] was saved to:
C:\Users\brian\auto-southwest-check-in\myenv\Lib\site-packages\seleniumbase\drivers\chromedriver.exe

Making [chromedriver.exe 122.0.6261.69] executable ...
[chromedriver.exe 122.0.6261.69] is now ready for use!


DevTools listening on ws://127.0.0.1:2832/devtools/browser/5154f20a-1b66-432f-b549-6c177c1475fe
Failed to log in to account with username USERNAME. Reason: Unknown. Status code: 400.

**Comment by jdholtz** [comment] 2024-02-26 20:47
@mrvizine glad to see the issue is fixed. As for the 400, you may be passing the wrong username (possibly?). Try putting the username and password in the config file to ensure your shell is not messing with the input.

**Comment by mrvizine** [comment] 2024-02-26 20:48
Yes it worked when I passed the username and password. It wouldn’t even get to that part before so now it for sure works. Thanks again

**Comment by jdholtz** [comment] 2024-02-26 20:58
Awesome. I'll close this issue and make sure to put `pip3` in the Readme instead of `pip`

**Closed by jdholtz** 2024-02-26 20:58 UTC
Labels: dependency
