### ISSUE TITLE
"Encountered a Too Many Requests error while logging in"

### ISSUE THREAD

**Issue by tcdo6666** [jdholtz/auto-southwest-check-in#214] opened 2024-01-31 03:31 UTC
### Version

Auto-Southwest Check-In v7.1

### Browser Version

Unknown, running docker jdholtz/auto-southwest-check-in:develop

### Description

Within the last 2w, started seeing this failure for account. Was originally running :latest but switched to develop in hope it would fix the issue. Same problem. 

### To Reproduce

1. Running docker with standard compose file using mapped config.json
2. Reviewed logs below when I haven't seen messages regarding most recent reservations. 

### Relevant logs and program output

```sh
2024-01-29 03:02:03 DEBUG MainProcess[log:23]: Initialized the application
2024-01-29 03:02:03 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.1
2024-01-29 03:02:03 DEBUG MainProcess[main:113]: Called with 0 arguments
2024-01-29 03:02:05 DEBUG MainProcess[config:107]: Initializing configuration file
2024-01-29 03:02:05 DEBUG MainProcess[config:135]: Reading the configuration file
2024-01-29 03:02:05 DEBUG MainProcess[config:53]: Setting check fares to True
2024-01-29 03:02:05 DEBUG MainProcess[config:67]: Setting notification level to <NotificationLevel.INFO: 1>
2024-01-29 03:02:05 DEBUG MainProcess[config:80]: Using 2 notification services
2024-01-29 03:02:05 DEBUG MainProcess[config:84]: Setting retrieval interval to 24 hours
2024-01-29 03:02:05 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2024-01-29 03:02:05 DEBUG MainProcess[config:125]: Creating configurations for 0 reservations
2024-01-29 03:02:05 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2024-01-29 03:02:08 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2024-01-29 03:02:08 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2024-01-29 03:02:08 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2024-01-29 03:02:08 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2024-01-29 03:02:22 DEBUG Process-1[webdriver:119]: Using browser version: 120.0.6099.224
2024-01-29 03:02:22 DEBUG Process-1[webdriver:123]: Loading Southwest Check-In page
2024-01-29 03:02:42 DEBUG Process-1[webdriver:80]: Logging into account to get a list of reservations and valid headers
2024-01-29 03:02:48 DEBUG Process-1[webdriver:152]: Waiting for headers_set to be set
2024-01-29 03:02:48 DEBUG Process-1[webdriver:156]: headers_set set successfully
2024-01-29 03:02:48 DEBUG Process-1[webdriver:144]: Login response has been received
2024-01-29 03:02:49 DEBUG Process-1[webdriver:152]: Waiting for login_request_id to be set
2024-01-29 03:02:49 DEBUG Process-1[webdriver:156]: login_request_id set successfully
2024-01-29 03:02:49 DEBUG Process-1[webdriver:212]: Logging in failed for an unknown reason
2024-01-29 03:02:49 WARNING Process-1[reservation_monitor:187]: Encountered a Too Many Requests error while logging in. Skipping reservation retrieval
2024-01-29 03:02:49 DEBUG Process-1[reservation_monitor:167]: Lock released
2024-01-29 03:02:49 DEBUG Process-1[reservation_monitor:116]: Sleeping for 86358 seconds
```

**Comment by jdholtz** [comment] 2024-01-31 03:38
Duplicate of #201.

**Closed by jdholtz** 2024-01-31 03:38 UTC
Labels: bug
