### ISSUE TITLE
Webdriver timed out in container

### ISSUE THREAD

**Issue by pldimarco** [jdholtz/auto-southwest-check-in#96] opened 2023-05-31 19:36 UTC
### Description

Using the latest (4.0) docker container, when I start the container, the webdriver session times out.

### To Reproduce

1. Create config with single flight
2. Start container with config file mounted
3. Wait ~10 minutes for timeout 

### Expected Behavior

Flight scheduled/monitored

### Version

`Auto-Southwest Check-In v4.0`

### Additional context

Logs:
```
2023-05-31 15:22:39 DEBUG MainProcess[log]: Initialized the application
2023-05-31 15:22:39 DEBUG MainProcess[main]: Called with 0 arguments
2023-05-31 15:22:40 DEBUG MainProcess[config]: Reading the configuration file
2023-05-31 15:22:40 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-05-31 15:22:40 DEBUG MainProcess[config]: Setting check fares to True
2023-05-31 15:22:40 DEBUG MainProcess[config]: Adding 1 flights from configuration file
2023-05-31 15:22:40 DEBUG MainProcess[config]: Setting notification level to 1
2023-05-31 15:22:40 DEBUG MainProcess[config]: Using 1 notification services
2023-05-31 15:22:40 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-05-31 15:22:40 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-05-31 15:22:40 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-05-31 15:22:40 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-05-31 15:22:40 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-05-31 15:22:40 DEBUG Process-1[webdriver]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/flight_retriever.py", line 36, in monitor_flights
    self._schedule_reservations(flights)
  File "/app/lib/flight_retriever.py", line 64, in _schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/app/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 59, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 142, in _get_driver
    driver = Chrome(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=112.0.5615.165)
```

**Comment by jdholtz** [comment] 2023-05-31 21:44
Thanks for filing this issue. Does this issue happen repeatedly or just once? 

I added better resistance to random webdriver initialization errors in the next version (will be released soon). If it just happens every once in a while, this added resistance should make this a non-issue

**Comment by pldimarco** [comment] 2023-05-31 22:26
It is happening repeatedly. Strangely, I do recall this version of the container working. So I'm not sure what has changed on the local container. Is the bundled chrome version able to auto update?

**Comment by jdholtz** [comment] 2023-05-31 22:36
It shouldn’t as long as you don’t specify a chrome version in your config file (that is handled in the Docker container itself)

**Comment by jdholtz** [comment] 2023-06-01 04:36
I just tried on the `jdholtz/auto-southwest-check-in:v4.0` image and it has repeatedly started the webdriver in less than a second for me. Therefore, it probably doesn't have anything to do with the image itself. Could something have possibly changed with your network configuration? There aren't too many variables that could make the image behave differently on your machine compared to mine. 

Could you also try the `:develop` image tag and see if that helps at all?

**Comment by pldimarco** [comment] 2023-06-01 13:39
I haven't set the chrome version in the config file. So I'm just using the bundled version. I tried the `:develop` tag and got similar results:
```
2023-06-01 09:27:13 DEBUG MainProcess[log]: Initialized the application
2023-06-01 09:27:13 DEBUG MainProcess[main]: Called with 0 arguments
2023-06-01 09:27:14 DEBUG MainProcess[config]: Reading the configuration file
2023-06-01 09:27:14 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-06-01 09:27:14 DEBUG MainProcess[config]: Setting check fares to True
2023-06-01 09:27:14 DEBUG MainProcess[config]: Adding 1 flights from configuration file
2023-06-01 09:27:14 DEBUG MainProcess[config]: Setting notification level to 1
2023-06-01 09:27:14 DEBUG MainProcess[config]: Using 1 notification services
2023-06-01 09:27:14 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-06-01 09:27:14 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-06-01 09:27:14 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-06-01 09:27:14 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-06-01 09:27:14 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-06-01 09:27:14 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-06-01 09:37:15 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: Name: TimeoutException. Error: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=113.0.5672.126)

2023-06-01 09:37:15 DEBUG Process-1[webdriver]: 2 more attempts
```

**Comment by jdholtz** [comment] 2023-06-05 13:11
Hey @pldimarco, do you have another machine you could test on to see if you get the same issue?

**Comment by Dominick-P** [comment] 2023-06-12 03:53
I'm experiencing the same thing with my container, webdriver will timeout 3 times then hard fail.

`
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=114.0.5735.90)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/flight_retriever.py", line 38, in monitor_flights
    self._schedule_reservations(flights)
  File "/app/lib/flight_retriever.py", line 66, in _schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/app/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 58, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 139, in _get_driver
    driver = self._init_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 181, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts
Process Process-1:
Traceback (most recent call last):
  File "/app/lib/webdriver.py", line 164, in _init_driver
    driver = Chrome(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=114.0.5735.90)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/flight_retriever.py", line 38, in monitor_flights
    self._schedule_reservations(flights)
  File "/app/lib/flight_retriever.py", line 66, in _schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/app/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 58, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 139, in _get_driver
    driver = self._init_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 181, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts
`

**Comment by stephenpapierski** [comment] 2023-06-12 18:05
I'm getting similar results on `Auto-Southwest Check-In v4.1`. I'm not using a config file and only passing in `USERNAME`/`PASSWORD`. I'm also running on Unraid and setting `privileged` helps as a temporary workaround.

**Comment by pldimarco** [comment] 2023-06-12 18:10
Confirmed that setting `privileged` on the container has worked around the issue.

**Comment by jdholtz** [comment] 2023-06-13 22:48
That's good to know that running with a privileged container works around this issue. Since I am not able to reproduce this issue, would you guys be able to manually add some code to see if this issue is solved? If not, I can push a new image with these fixes to which you can test.

On line 207 of `lib/webdriver.py`, add the following lines of code (make sure the indentation is correct). You can mix and match these lines to see which ones are needed and which ones aren't.
```python
options.add_argument("--disable-gpu")
options.add_argument("--disable-extensions")
options.add_argument("--dns-prefetch-disable")
```

To add this in the Docker image, you can first run the following command: `docker run -d --entrypoint sleep jdholtz/auto-southwest-check-in infinity`. 

Then, exec into it by doing `docker exec -it <container-name> sh`. 

You can edit the file by using `vi lib/webdriver.py` and then run the script inside the container by doing `python southwest.py USERNAME PASSWORD`.

**Comment by jdholtz** [comment] 2023-06-16 15:54
Yes, you can grab a screenshot at any point with `driver.save_screenshot("file_name.png")`. Just place that at any point in the code where you want a screenshot of the page.

It seems like the initial timeout issue is solved, but it just doesn't load the page elements. Have you tried to use each of the new options I suggested individually? You may only need one of them to fix the original issue and this new timeout my be the cause of an option not needed.

**Comment by stgreenb** [comment] 2023-06-17 15:07
same issue, --privileged fixed it.

**Comment by jdholtz** [comment] 2023-06-18 14:27
Is everyone who has this issue running the Docker container on an Unraid host? pldimarco and stephenpapierski appear to be so maybe there is a conflict between this script and Unraid hosts.

**Comment by Dominick-P** [comment] 2023-06-18 14:35
I’m running it on a standard Ubuntu 22.04.1 LTS installation using docker run and portainer for managing my containers

**Comment by stgreenb** [comment] 2023-06-18 15:00
Ubuntu 22.04.2 LTS

**Comment by jdholtz** [comment] 2023-06-25 13:47
Hey @pldimarco, any updates to my comment [here](https://github.com/jdholtz/auto-southwest-check-in/issues/96#issuecomment-1594905457) ?

**Comment by pldimarco** [comment] 2023-06-25 14:34
@jdholtz 

I tried one additional flag at a time and no one flag worked. I didn't try the combinations of 2 flags. But three flags has gotten it to `Loading Southwest Check-In page`.

I wasn't able to grab a screenshot. Because while I got past the `driver = self._init_driver()` line, the line where it is stuck is `driver.get(CHECKIN_URL)`. I put a debug line after that statement to confirm it wasn't returning. That's about how far I've gotten with it recently.

**Comment by jdholtz** [comment] 2023-06-25 15:03
That makes sense. Thanks for trying. 

Would you be able to try something else so we can see if this issue is directly with the Chromedriver or with this script? 

Enter the Docker container and type `python` (or `python3`) to enter the Python terminal. Then paste the following code and see if it still times out:
```python

from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
options = ChromeOptions()
options.add_argument("--headless=new")
driver = Chrome(driver_executable_path="/usr/bin/chromedriver", options=options)
driver.get("https://mobile.southwest.com/check-in")
```

If it finishes without timing out, then it is most likely due to the configuration this script uses.

**Comment by pldimarco** [comment] 2023-06-25 15:44
I put the code into a script and ran it. And it just hanged. So I put prints between each step, so my script looked like:
```
from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
print("1")
options = ChromeOptions()
print("2")
options.add_argument("--headless=new")
print("3")
driver = Chrome(driver_executable_path="/usr/bin/chromedriver", options=options)
print("4")
driver.get("https://mobile.southwest.com/check-in")
print("5")
```
And the last I saw was `3`.

**Comment by jdholtz** [comment] 2023-06-25 16:33
I really appreciate you taking your time to debug this. Unfortunately, this means the issue doesn’t directly have to do with this script as the issue is reproducible without using this script at all. 

Currently, I’m not sure how to debug this further. You can try to test the [Selenium Docker Image](https://github.com/SeleniumHQ/docker-selenium) (for Chrome) to see if you still receive a timeout. That repository has also fixed some timeout issues too, so it might be worth it to try to exec into the Southwest script image and do `export DBUS_SESSION_BUS_ADDRESS=/dev/null` before running the script manually (suggestion from [this issue](https://github.com/SeleniumHQ/docker-selenium/issues/87)).

**Comment by wootwoot1234** [comment] 2023-07-02 17:40
I'm also having this issue running on mac os.  It was working before, then I updated it and now it's not.  I'm not sure how to fix it.

**Comment by jdholtz** [comment] 2023-07-02 18:29
Hey @wootwoot1234, it seems like running the Docker container with the `--privileged` flag works around this issue. You can also try my suggestions about the Selenium Docker image in the above comment to potentially see what the problem is on a deeper level.

**Comment by wootwoot1234** [comment] 2023-07-02 19:14
@jdholtz thanks, running it as a docker image worked great except I couldn't get it to load my config file so I had to pass it the username/passwrod as ARGS.  

BTW, the docs could be a little clearer.  I wasn't clear to me that I was supposed to replace `ARGS` with my username and password.  I eventually figured it out but It might be clearer if instead of `ARGS` you but `USERNAME PASSWORD` or `CONFIRMATION FIRST LAST`

**Comment by jdholtz** [comment] 2023-07-02 19:35
Good to hear. The paragraph below the `docker run` command explains how to pass in your config file. 

Thanks for your note on the `ARGS`. I will modify the docs to make it more clear.

**Comment by jdholtz** [comment] 2023-07-07 23:23
Has anyone that is running into this issue tried my suggestions [here](https://github.com/jdholtz/auto-southwest-check-in/issues/96#issuecomment-1606151852)?

**Comment by pldimarco** [comment] 2023-07-08 12:51
Hey @jdholtz. I went to try out your suggestions here as I was traveling for a bit and I now cannot reproduce the issue. So I disabled `privileged` on the container and it is working now. I did recently upgrade unraid to 6.12.2 (CC: @stephenpapierski) which may have had an effect. But I know other users were reporting the issue.

**Comment by jdholtz** [comment] 2023-07-08 13:12
That’s good to hear but strange why this issue has unknowingly disappeared. Thank you for all the debugging you’ve done for this issue!

**Comment by jdholtz** [comment] 2023-07-23 19:50
Since this issue is resolved for the author and no one else has reported back that the issue still occurs for them after trying my [suggestions](https://github.com/jdholtz/auto-southwest-check-in/issues/96#issuecomment-1606151852) above, I will close this.

If you are still running into this issue (even after my suggestions), please either comment on this issue or open a separate issue.

**Closed by jdholtz** 2023-07-23 19:50 UTC
Labels: bug

**Comment by txssseal** [comment] 2023-08-03 02:57
Im running into this issue doing a direct install on Ubuntu 22.04.

`Process` Process-1:
Traceback (most recent call last):
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/webdriver.py", line 164, in _init_driver
    driver = Chrome(
  File "/home/creeks-edge/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/creeks-edge/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1738, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self.checkin_scheduler.refresh_headers()
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/webdriver.py", line 59, in set_headers
    driver = self._get_driver()
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/webdriver.py", line 139, in _get_driver
    driver = self._init_driver()
  File "/home/creeks-edge/code/auto-southwest-check-in/lib/webdriver.py", line 181, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts`

**Comment by jdholtz** [comment] 2023-08-03 03:29
@txssseal do you have a Chromium browser installed (such as Google Chrome)?

**Comment by jdholtz** [comment] 2023-08-17 03:30
> I was able to run the above, but I think you're missing the line that times out,

This timeout happens at different places for everyone affected by the issue (the OP timed out when initializing Chrome, for example).

I'm not able to reproduce this, so it appears to be a network issue that people run into every so often (maybe Southwest has something to do with this, but I'm doubtful). For reference, I am using Chrome v116 (with the workaround in the pinned issue), but I don't know what else could be causing this. It appears to go away for people who run into this issue eventually because no one has reported that they are still running into the timeout.

**Comment by jdholtz** [comment] 2023-08-17 03:46
It could be a selenium-wire issue. You can try to replace the import statement with `from undetected_chromedriver import Chrome, ChromeOptions` and see if you still get the timeout.

**Comment by jdholtz** [comment] 2023-12-21 00:21
> running it still requires --privileged to work.

Thanks for the update. I still haven’t run into this issue at all. What OS are you running?
