### ISSUE TITLE
Failed to check in to flight [CONF#] for [NAME]. Reason: Bad Request 400.

### ISSUE THREAD

**Issue by pizzamark** [jdholtz/auto-southwest-check-in#272] opened 2024-06-07 18:37 UTC
### Version

Auto-Southwest Check-In v7.4

### Browser Version

Unsure how to check?

### Description

These are the flights attached to each confirmation:
 Flight from Orlando to Buffalo/Niagara on 2024-06-01 7:05 AM EDT
 Flight from Buffalo/Niagara to Orlando on 2024-06-09 7:45 AM EDT

I am attempting to run the script on June 6, as I did not leave it running after it successfully checked me in on June 1. 

I've tried several times and receive the following error msgs:
 Failed to check in to flight [CONF#] for [NAME]. 
  1. Reason: Bad Request 400.
  2. Reason: Too Many Requests 429.

For troubleshooting I set check_fares to false and the issue persists - so what it appears to be doing is trying to check in my old flight from June 1. Curious if this is a bug or if the expectation is to leave the script open for the duration of both the check-ins, from each leg of a round-trip flight?

Thank you.
 

### To Reproduce

Run script after one leg of of a round-trip flight has been completed.

**Comment by pizzamark** [comment] 2024-06-07 18:42
Upon a closer look at the logs it's unclear if the sleep time is not being honored or if it's truly trying to check in the old flights.

2024-06-07 14:31:35 DEBUG Process-2[webdriver:149]: Using browser version: 125.0.6422.142
2024-06-07 14:31:35 DEBUG Process-2[webdriver:153]: Loading Southwest Check-In page
2024-06-07 14:31:42 DEBUG Process-2[webdriver:88]: Waiting for valid headers
2024-06-07 14:31:42 DEBUG Process-2[webdriver:182]: Waiting for headers_set to be set
2024-06-07 14:31:42 DEBUG Process-2[webdriver:186]: headers_set set successfully
2024-06-07 14:31:44 DEBUG Process-2[reservation_monitor:86]: Scheduling flight check-ins for 1 reservations
2024-06-07 14:31:44 DEBUG Process-2[checkin_scheduler:78]: Retrieving reservation information
2024-06-07 14:31:46 DEBUG Process-2[utils:34]: Successfully made request after 1 attempts
2024-06-07 14:31:46 DEBUG Process-2[checkin_scheduler:91]: Successfully retrieved reservation information
2024-06-07 14:31:46 DEBUG Process-2[checkin_scheduler:58]: 2 flights found under current reservation
2024-06-07 14:31:46 DEBUG Process-2[checkin_scheduler:44]: 2 total flights were found
2024-06-07 14:31:46 DEBUG Process-2[checkin_scheduler:109]: 2 new flights found
2024-06-07 14:31:46 DEBUG Process-2[checkin_scheduler:113]: Scheduling 2 flights for check-in
2024-06-07 14:31:46 DEBUG Process-2[checkin_handler:47]: Scheduling check-in for current flight
2024-06-07 14:31:46 DEBUG Process-2[checkin_handler:47]: Scheduling check-in for current flight
2024-06-07 14:31:46 DEBUG Process-2[notification_handler:69]: Sending new flights notification
2024-06-07 14:31:47 DEBUG Process-2:1[checkin_handler:87]: Check-in time has passed. Going straight to check-in
2024-06-07 14:31:47 DEBUG Process-2:1[checkin_handler:128]: Attempting to check in
2024-06-07 14:31:47 DEBUG Process-2:1[checkin_handler:156]: Submitting check-in with a POST request
2024-06-07 14:31:47 DEBUG Process-2:1[checkin_handler:188]: Making GET request to check in
2024-06-07 14:31:47 DEBUG Process-2:2[checkin_handler:95]: Sleeping until thirty minutes before check-in...
2024-06-07 14:31:47 DEBUG Process-2[checkin_scheduler:125]: 2 flights are currently scheduled. Removing old flights
2024-06-07 14:31:47 DEBUG Process-2[checkin_scheduler:141]: Successfully removed old flights. 2 flights are now scheduled
2024-06-07 14:31:47 DEBUG Process-2[reservation_monitor:82]: Lock released
2024-06-07 14:31:47 DEBUG Process-2[reservation_monitor:130]: Sleeping for 86364 seconds
2024-06-07 14:32:05 DEBUG Process-1:1[utils:48]: Failed to make request after 21 attempts: Bad Request 400
2024-06-07 14:32:05 DEBUG Process-1:1[utils:50]: Response body: {"code":400308191,"message":"It is too early to check in for this trip. You can check in 24 hours before departure. Come back on Jun 8, 2024 when it is 7:45AM in Buffalo/Niagara","messageKey":"ERROR__AIR_TRAVEL__BEFORE_CHECKIN_WINDOW","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"no-exp-id:0.cfd07868.1717785123.a2ae1005:mweb","infoList":[]}
2024-06-07 14:32:05 DEBUG Process-1:1[checkin_handler:137]: Failed to check in. Error: Bad Request 400. Exiting
2024-06-07 14:32:05 DEBUG Process-1:1[notification_handler:112]: Sending failed check-in notification...
2024-06-07 14:32:23 DEBUG Process-2:1[utils:48]: Failed to make request after 21 attempts: Bad Request 400
2024-06-07 14:32:23 DEBUG Process-2:1[utils:50]: Response body: {"code":400308191,"message":"It is too early to check in for this trip. You can check in 24 hours before departure. Come back on Jun 8, 2024 when it is 7:45AM in Buffalo/Niagara","messageKey":"ERROR__AIR_TRAVEL__BEFORE_CHECKIN_WINDOW","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"no-exp-id:0.ced07868.1717785141.ca12bf9f:mweb","infoList":[]}
2024-06-07 14:32:23 DEBUG Process-2:1[checkin_handler:137]: Failed to check in. Error: Bad Request 400. Exiting
2024-06-07 14:32:23 DEBUG Process-2:1[notification_handler:112]: Sending failed check-in notification...

**Comment by jdholtz** [comment] 2024-06-08 02:34
@pizzamark could you try on the `develop` branch? This may be a duplicate of #257. To use the branch, run `git pull && git checkout develop`.

**Comment by jdholtz** [comment] 2024-06-14 04:13
Closing as this is probably a duplicate and should be fixed in v7.5

**Closed by jdholtz** 2024-06-14 04:13 UTC
Labels: bug
