### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by babehboi** [jdholtz/auto-southwest-check-in#127] opened 2023-07-25 15:06 UTC
### Description

Updated from 4.1 > 4.3 today, started the script like usual, and getting 404 errors.

I have attempted to ping and access websites and they are accessible.

What I've been able to determine is that the "chrome_version" parameter may be at fault? 

My current chrome version is 115.x, originally I've left it 113. But eventually moved the version on the config file to 115 after 113 had the error. 

Despite the update, error still ensues, decided to remove it entirely, and the script works.

### To Reproduce

1. Run script with a config file where you use "chrome_version" as a parameter.

2023-07-25 07:43:29 DEBUG MainProcess[log:23]: Initialized the application
2023-07-25 07:43:29 DEBUG MainProcess[main:112]: Called with 0 arguments
2023-07-25 07:43:29 DEBUG MainProcess[config:110]: Initializing configuration file
2023-07-25 07:43:29 DEBUG MainProcess[config:138]: Reading the configuration file
2023-07-25 07:43:29 DEBUG MainProcess[config:58]: Setting check fares to True
2023-07-25 07:43:29 DEBUG MainProcess[config:70]: Setting notification level to <NotificationLevel.INFO: 1>
2023-07-25 07:43:29 DEBUG MainProcess[config:83]: Using 2 notification services
2023-07-25 07:43:29 DEBUG MainProcess[config:87]: Setting retrieval interval to 24 hours
2023-07-25 07:43:29 DEBUG MainProcess[config:155]: Setting chrome version to 115
2023-07-25 07:43:29 DEBUG MainProcess[config:121]: Creating configurations for 1 accounts
2023-07-25 07:43:29 DEBUG MainProcess[config:128]: Creating configurations for 4 reservations
2023-07-25 07:43:29 DEBUG MainProcess[main:141]: Monitoring 1 accounts and 4 reservations
2023-07-25 07:43:30 DEBUG Process-1[reservation_monitor:176]: Retrieving reservations for account
2023-07-25 07:43:30 DEBUG Process-1[webdriver:138]: Starting webdriver for current session
2023-07-25 07:43:30 DEBUG Process-2[checkin_scheduler:50]: Refreshing headers for current session
2023-07-25 07:43:30 DEBUG Process-2[webdriver:138]: Starting webdriver for current session
2023-07-25 07:43:30 DEBUG Process-3[checkin_scheduler:50]: Refreshing headers for current session
2023-07-25 07:43:30 DEBUG Process-3[webdriver:138]: Starting webdriver for current session
2023-07-25 07:43:30 DEBUG Process-4[checkin_scheduler:50]: Refreshing headers for current session
2023-07-25 07:43:30 DEBUG Process-4[webdriver:138]: Starting webdriver for current session
2023-07-25 07:43:30 DEBUG Process-5[checkin_scheduler:50]: Refreshing headers for current session
2023-07-25 07:43:30 DEBUG Process-5[webdriver:138]: Starting webdriver for current session
2023-07-25 07:43:30 DEBUG Process-2[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-2[webdriver:178]: 2 more attempts
2023-07-25 07:43:30 DEBUG Process-3[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-3[webdriver:178]: 2 more attempts
2023-07-25 07:43:30 DEBUG Process-1[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-1[webdriver:178]: 2 more attempts
2023-07-25 07:43:30 DEBUG Process-5[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-5[webdriver:178]: 2 more attempts
2023-07-25 07:43:30 DEBUG Process-4[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-4[webdriver:178]: 2 more attempts
2023-07-25 07:43:30 DEBUG Process-3[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-3[webdriver:178]: 1 more attempts
2023-07-25 07:43:30 DEBUG Process-2[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-2[webdriver:178]: 1 more attempts
2023-07-25 07:43:30 DEBUG Process-5[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-5[webdriver:178]: 1 more attempts
2023-07-25 07:43:30 DEBUG Process-1[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-1[webdriver:178]: 1 more attempts
2023-07-25 07:43:30 DEBUG Process-4[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:30 DEBUG Process-4[webdriver:178]: 1 more attempts
2023-07-25 07:43:33 DEBUG Process-1[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:33 DEBUG Process-3[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:33 DEBUG Process-1[webdriver:178]: 0 more attempts
2023-07-25 07:43:33 DEBUG Process-3[webdriver:178]: 0 more attempts
2023-07-25 07:43:33 DEBUG Process-2[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:33 DEBUG Process-2[webdriver:178]: 0 more attempts
2023-07-25 07:43:33 DEBUG Process-5[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:33 DEBUG Process-5[webdriver:178]: 0 more attempts
2023-07-25 07:43:33 DEBUG Process-4[webdriver:172]: An exception occurred when initializing the webdriver: Name: HTTPError. Error: HTTP Error 404: Not Found
2023-07-25 07:43:33 DEBUG Process-4[webdriver:178]: 0 more attempts

### Version

4.3

**Comment by jdholtz** [comment] 2023-07-25 17:00
Thanks for reporting this. I can reproduce this issue as well. It seems that the chromedriver download moved locations for version 115 (see [here](https://chromedriver.chromium.org/downloads)). While we are waiting for this to be fixed (most likely in undetected_chromedriver), you can either not specify a version or specify version 114.

**Comment by jdholtz** [comment] 2023-07-31 02:45
There is currently a pull request to fix this issue in Undetected Chromedriver. However, the other issue is that Selenium Wire doesn't work with the latest version of Undetected Chromedriver, but I made a PR to fix that in the Selenium Wire repository. Unfortunately, it doesn't appear the selenium-wire owner is very active right now so that fix might not be merged for a while.

The good thing is that the fix for this issue currently is to just specify `chrome_version: 114` if you want to use Chrome v115.

**Comment by jdholtz** [comment] 2023-08-05 03:13
I'll close this issue for now since there is `chrome_version: 114` can be specified in the `config.json` and this is an upstream bug.

**Closed by jdholtz** 2023-08-05 03:13 UTC
Labels: bug
