### ISSUE TITLE
chromedriver cannot connect to chrome

### ISSUE THREAD

**Issue by thegunz** [jdholtz/auto-southwest-check-in#39] opened 2023-02-08 23:12 UTC
Worked on Monday for my checkin, then stopped today on my return flight.  Chrome was 109 when this first error was thrown:  
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65194
from session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 109.0.5414.121

So I opened chrome and let it update to 110.  Then ran the script again and got this error: 
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65324
from unknown error: unable to discover open pages

**Comment by jdholtz** [comment] 2023-02-09 00:39
Hi. Thanks for reporting this. I can reproduce the issue. It seems like Google changed the way `headless` in Chrome works as of version 110. This was fixed in version `3.4.5` of `undetected_chromedriver` (see [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver#345)). To update you can run `pip install -U undetected_chromedriver`.

However, I am getting a 429 error when trying to set up my account. Does this error occur for you as well? It might be with the recent changes in `undetected_chromedriver`.

**Comment by jdholtz** [comment] 2023-02-09 01:48
Hey @thegunz, I provided a fix for this on the [chrome_configuration](https://github.com/jdholtz/auto-southwest-check-in/tree/chrome_configuration) branch. Can you downgrade Google Chrome to 109 and download Chromedriver version 109 (can be found [here](https://chromedriver.chromium.org/downloads)). Also, make sure `undetected_chromedriver` is the version in the `requirements.txt` because the new version seems to have some issues.

To get those changes, run `git pull && git checkout chrome_configuration` and make sure to specify `chromedriver_path` in the `config.json` (you can see the details in the Configuration Doc).

**Comment by darrylwhiting** [comment] 2023-02-09 03:24
It appears that upgrading undetected_chromedriver to 3.4.5 allows me to use the CONFIRMATION_NUMBER FIRST_NAME LAST_NAME method with Chrome 110.0.5481.78. I see the correct UTC time for my departing flight with a valid check-in timeframe about 8 hours from now. Am I risking a possible error that mean my flight won't check-in?

**Comment by jdholtz** [comment] 2023-02-09 03:32
I haven’t been able to test undetected chromedriver 3.4.5 (it wasn’t working for me), so I don’t know for sure if it will work. If you do decide to proceed, please let me know if it works.

**Comment by darrylwhiting** [comment] 2023-02-09 03:59
When using username and password I get the following: KeyError: 'customers.userInformation.firstName'

**Comment by darrylwhiting** [comment] 2023-02-09 04:08
Ya, I am getting 429 as well:
{'code': 429999999, 'message': 'Error.', 'messageKey': 'ERROR', 'httpStatusCode': 'BAD_REQUEST', 'requestId': '', 'infoList': []}

**Comment by darrylwhiting** [comment] 2023-02-09 11:51
Checking in to flight from 'Blah' to 'Meh' for JOHN DOE

Failed to check in to flight 1A2WXYZ for JOHN DOE Reason: Too Many Requests 429.
Check in at this url: https://mobile.southwest.com/check-in

And also when I logged into the .com site, and then did a manual check in, I got an error about "appendChild" that was thrown by Southwest.com, and I had to use a different Check-in button, so I wonder if this is partly on the SW's side?

**Comment by jdholtz** [comment] 2023-02-09 12:04
That’s strange. Unfortunately, I don’t have any upcoming flights to try, so I won’t be able to test this for a while. Hopefully it is just from Southwest’s side and they fix it soon.

**Comment by thegunz** [comment] 2023-02-09 16:01
I was not able to downgrade to chrome 109 on my managed work PC, so I
upgraded undetected_chromedriver to 3.4.5.  I ran the script for a flight I
have today (already checked in) hoping I'd at least see a successful
outcome telling me my boarding position.  Unfortunately, got this error
result (removed my conf # & name):

Failed to check in to flight XXXX for [firstname] [lastname] Reason: Too
Many Requests 429.
Check in at this url: https://mobile.southwest.com/check-in

Hopefully this will help troubleshoot the issue

**Comment by jdholtz** [comment] 2023-02-09 17:15
Yeah, this is the current issue I get as well when trying to log in. `undetected_chromedriver` changed some of its anti-bot algorithms, so that could be the issue. I’ll keep up with the undetected_chromedriver repository and hopefully they will have a fix soon.

**Comment by zderick** [comment] 2023-02-10 04:58
I was able to overcome this by downloading an older version of chrome. 108 in my case from here: http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/

And then adding a parameter when we initialize the driver here: https://github.com/jdholtz/auto-southwest-check-in/blob/master/lib/webdriver.py#L44

`Chrome(options=self.options, ..., version_main=108)`

**Comment by jdholtz** [comment] 2023-02-10 14:18
Thanks for testing @zderick. I was also able to test with the same parameters on version 109 with success.

Here are my results from doing different tests:
- With Undetected ChromeDriver v3.4.5, the script doesn't log in successfully with any version of Chrome.
- With Undetected ChromeDriver v3.1.7 (the current version in the script), the script logs in successfully with Chrome v108 (@zderick's testing) and v109. However, it doesn't work with Chrome version 110.

I assume the current script works with any Chrome version <= 109. Instead of adding the ChromeDriver path to the configuration, I can allow users to specify the chrome version. Then, the script can limit Google Chrome versions to <= 109 until v110+ works with `undetected_chromedriver`.

Can anyone verify a check-in works using Chrome version <= 109? You can follow what @zderick did above to specify the version. If you can't figure that out, let me know and I will create a branch so you can specify the version in the configuration file.

**Comment by darrylwhiting** [comment] 2023-02-10 14:36
If the status is the same by next Friday, I can try again with an older version of Chrome (v109). I actually prefer this since another site I regularly "watch" may have broken too. :)

**Comment by molmedo1** [comment] 2023-02-10 15:18
> Thanks for testing @zderick. I was also able to test with the same parameters on version 109 with success.
> 
> Here are my results from doing different tests:
> 
> * With Undetected ChromeDriver v3.4.5, the script doesn't log in successfully with any version of Chrome.
> * With Undetected ChromeDriver v3.1.7 (the current version in the script), the script logs in successfully with Chrome v108 (@zderick's testing) and v109. However, it doesn't work with Chrome version 110.
> 
> I assume the current script works with any Chrome version <= 109. Instead of adding the ChromeDriver path to the configuration, I can allow users to specify the chrome version. Then, the script can limit Google Chrome versions to <= 109 until v110+ works with `undetected_chromedriver`.
> 
> Can anyone verify a check-in works using Chrome version <= 109? You can follow what @zderick did above to specify the version. If you can't figure that out, let me know and I will create a branch so you can specify the version in the configuration file.


flying tomorrow and didnt come here to check issue unfotunately. I got the too many request error even though i changed the chromedriver options to 109 . NOW i have downgraded UC to 3.1.7 and using chromev109. I fly back Sunday. Will test and report back

**Comment by jdholtz** [comment] 2023-02-10 20:15
I added the option to specify the chrome version in the `config.json` in the [chrome_version](https://github.com/jdholtz/auto-southwest-check-in/tree/chrome_version) branch. There isn't documentation on it yet, but you can view the `config.example.json` for an example on how to use it. Just input the main version (108, 109, etc.). The default is 109.

**Comment by everettsouthwick** [comment] 2023-02-10 20:35
> I added the option to specify the chrome version in the `config.json` in the [chrome_version](https://github.com/jdholtz/auto-southwest-check-in/tree/chrome_version) branch. There isn't documentation on it yet, but you can view the `config.example.json` for an example on how to use it. Just input the main version (108, 109, etc.). The default is 109.
> 
> Note: It does not work in Docker yet

I made some local changes to the Dockerfile that may help:
```
ARG CHROME_VERSION="109.0.5414.119-1"
RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
  && apt install -y /tmp/chrome.deb \
  && rm /tmp/chrome.deb
```

Modified from here: https://unix.stackexchange.com/questions/233185/install-older-versions-of-google-chrome-stable-on-ubuntu-14-10

**Comment by jdholtz** [comment] 2023-02-10 21:48
Thanks @everettsouthwick! I will use that to make changes in the Dockerfile (or you can submit a PR), but I’ll wait for verification that a check-in works first.

**Comment by molmedo1** [comment] 2023-02-12 16:00
> > Thanks for testing @zderick. I was also able to test with the same parameters on version 109 with success.
> > Here are my results from doing different tests:
> > 
> > * With Undetected ChromeDriver v3.4.5, the script doesn't log in successfully with any version of Chrome.
> > * With Undetected ChromeDriver v3.1.7 (the current version in the script), the script logs in successfully with Chrome v108 (@zderick's testing) and v109. However, it doesn't work with Chrome version 110.
> > 
> > I assume the current script works with any Chrome version <= 109. Instead of adding the ChromeDriver path to the configuration, I can allow users to specify the chrome version. Then, the script can limit Google Chrome versions to <= 109 until v110+ works with `undetected_chromedriver`.
> > Can anyone verify a check-in works using Chrome version <= 109? You can follow what @zderick did above to specify the version. If you can't figure that out, let me know and I will create a branch so you can specify the version in the configuration file.
> 
> flying tomorrow and didnt come here to check issue unfotunately. I got the too many request error even though i changed the chromedriver options to 109 . NOW i have downgraded UC to 3.1.7 and using chromev109. I fly back Sunday. Will test and report back

Using config file with v109 and UC 3.1.7 worked like a charm!!! Was able to add multiple conf# which I forgot the script could do. B06&B07 not bad. Thanks everyone.

**Comment by ryanjchan** [comment] 2023-02-12 18:39
For what its worth, I was getting the same WebDriverExceptions and only updated UC (undetected-chromedriver==3.4.6). I do not have issues reading the reservation page anymore so I assume the checkin should work as well.

The chrome I am running is - Google Chrome 110.0.5481.77

**Comment by jdholtz** [comment] 2023-02-12 19:15
@molmedo1 glad to hear it worked. I will merge the latest changes from the `chrome_version` branch, and then I can release version 2!

**Comment by jdholtz** [comment] 2023-02-12 19:19
@ryanjchan could you try to log in? You can see in [this](https://github.com/jdholtz/auto-southwest-check-in/issues/39#issuecomment-1424063899) comment that it scheduled the check-in successfully but still failed to actually perform the check in. I am also trying with the latest version of Chrome and undetected_chromedriver and getting a 429 error when trying to log in.

**Comment by ryanjchan** [comment] 2023-02-12 20:28
> 
I get a 404 when attempting the checkin since it is too soon? (Not sure what the behavior is, should this url only work if its within the checkin window?)

When checking the .com the url returns {"code":400120102,"message":"","httpStatusCode":"BAD_REQUEST","requestId":"","infoList":[""]}

The initial GET for a checkin fails (mobile-air-operations/v1/mobile-air-operations/page/check-in/) so I never get to the POST to checkin.

 I'll try to check the output when the flight comes around later this week.

**Comment by jdholtz** [comment] 2023-02-12 20:50
Yes, that 404 is expected. You can see that happen on the Southwest website as well.

**Comment by vdude8** [comment] 2023-02-13 11:44
Just a quick comment (maybe this is already known): I was having the same issue, and I changed the headless mode in webdriver.py by adding the argument "--headless=new". Based on what I'm reading, it should be "--headless=chrome" for versions 96-108, and 109 and beyond should be set to "new". Just checked into two flights now on Chrome 110!

source: https://www.selenium.dev/blog/2023/headless-is-going-away/

**Comment by jdholtz** [comment] 2023-02-13 20:38
Thanks @vdude8 for finding this! This was implemented in the latest versions of `undetected_chromedriver`, but I'm still getting detected by Southwest so I just ported that feature to the `chrome_version` branch.

**Comment by jdholtz** [comment] 2023-02-13 23:39
Hey @everettsouthwick, I tried to implement the Docker version specification, but I couldn't figure out a way to simultaneously allow the user to download the latest version automatically or a specific version if specified. If anyone else figures it out, feel free to make a pull request.

**Closed** 2023-02-14 00:12 UTC
Labels: bug
