### ISSUE TITLE
Error 429 with Chrome v110

### ISSUE THREAD

**Issue by ctkubik** [jdholtz/auto-southwest-check-in#43] opened 2023-02-14 03:54 UTC
### Description

I know this is a known issue that I have been following.  I am not sure if the issue was corrected for <110 or up to and including Chrome 110 with v2.

I updated to v2 
I updated my json file to include "chrome_version": 110
I ran the --requirements.txt script 
The webdriver file is confirmed to have the options.add_argument("--headless=new") entry.  

What else am I missing?   Should I have the undetected-chromedriver 3.4.6 or 3.1.7?  I tried both and neither work...

### To Reproduce

southwest.py USERNAME PASSWORD

Failed to log in to account with username XXXXXXXXX. Status Code: 429.
Make sure the login information is correct and try again.

### Version

Auto-Southwest Check-In v2.0

**Comment by jdholtz** [comment] 2023-02-14 12:47
Hi. The script should work with any supported Chrome version. I'm not able to reproduce this with Google Chrome 110.0.5481.96. Can you reproduce the issue with Chrome v109?

`undetected_chromedriver` version 3.4.6 does not work with this script, so you will need the same version that is in the `requirements.txt`.

Do you have any special characters in your username or password? That could be the cause as the correct password doesn't get parsed.

**Comment by ctkubik** [comment] 2023-02-14 13:32
I deleted the login information for my 3 accounts out of the json file and logged in manually to one account (with special characters).  It seems like the first account I log into can use a script (either in my json file or a vbs I created).  The accounts after the first seem to throw an error.  If I use the script they throw a 429 error...when I log in manually I get the error below.  

Successfully scheduled the following flights to check in for FIRST LAST:
Flight from ORIGIN to DESTINATION at 2023-04-02 19:45:00 UTC
Flight from ORIGIN to DESTINATION at 2023-04-29 12:45:00 UTC

Process Process-1:2:
Traceback (most recent call last):
  File "C:\Users\ctkub\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ctkub\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ctkub\Desktop\Southwest Checkin\lib\checkin_handler.py", line 40, in _set_check_in
    self._wait_for_check_in(checkin_time)
  File "C:\Users\ctkub\Desktop\Southwest Checkin\lib\checkin_handler.py", line 53, in _wait_for_check_in
    time.sleep(sleep_time)
OverflowError: sleep length is too large

**Comment by jdholtz** [comment] 2023-02-14 14:42
The "sleep length too large" error is an actual error with the script because it is scheduling it too far into the future. Can you open a separate issue for that when you get a chance?

As for the special characters, try to escape them in the command line or config file (you can escape every character if you are unsure which ones to escape: `password` -> `\p\a\s\s\w\o\r\d`. If you really want, you can also see how they are entered by adding `print(arguments)` or `print(config.accounts)` on line 99 of `lib/main.py`.

**Comment by ctkubik** [comment] 2023-02-14 16:08
I added the print function and it seems to be sending the account information fine.  

So...this is what I see when I use my script

![image](https://user-images.githubusercontent.com/10108275/218792216-a4ea663e-c447-48e7-9f5d-3d62d504f2c6.png)

Ironically...now I cannot manually enter my information either.

**Comment by jdholtz** [comment] 2023-02-14 17:14
Can you try the same with Chrome v109? This could help narrow down the issue more.

**Comment by ctkubik** [comment] 2023-02-14 17:18
It actually worked perfectly with 109.  I had 3 vbs scripts which worked great and then I switched that to the json file and it also worked.  Sadly my system automatically updated (which I now turned off), so I no longer have a way to run 109.  I uninstalled and tried finding an installer...but I just didn't have the time to commit to figuring out how to downgrade.

**Comment by jdholtz** [comment] 2023-02-14 17:30
That's strange it worked for one account but not the other two. If anyone else runs into this issue, hopefully they can report it here too so we know it is definitely an issue with v110. 

One last thing: If you have Docker set up, could you try running the container for the script and see if it does the same (If it isn't set up, don't worry about it)?

**Comment by ctkubik** [comment] 2023-02-14 17:51
Well...this is even more odd.  I can no longer log into any of my accounts (entering it in manually).  I can log in a future flight using the confirmation and my name.  

I do not have Docker...only Windows.

**Comment by jdholtz** [comment] 2023-02-14 18:06
From other people's testing, it does seem like Chrome version 110 allows you to schedule flights, but it fails when checking you in. Therefore, it probably won't check you in successfully if you can't log in now.

**Comment by ctkubik** [comment] 2023-02-14 18:08
Gotcha!  Sorry...I wasn't sure if that was fixed or not.  That means I am having the same experience.  I appreciate the help!

**Comment by ctkubik** [comment] 2023-02-14 18:29
I am not sure what I am doing wrong.  It worked great using the Develop channel.  Once Chrome updated it has created this issue.  I updated to v2...I can add individual flights, but I cannot log in.  I have 110.0.5481.97 64-bit installed.

**Comment by jdholtz** [comment] 2023-02-14 19:51
It doesn't appear you are doing anything wrong. I'll keep up with the undetected_chromedriver repository to see if they fix the current version. If you do need it now, you can try to run it in Docker.

**Comment by darrylwhiting** [comment] 2023-02-17 13:53
> I am not sure what I am doing wrong. It worked great using the Develop channel. Once Chrome updated it has created this issue. I updated to v2...I can add individual flights, but I cannot log in. I have 110.0.5481.97 64-bit installed.

Just to confirm I am also seeing the same behavior as @ctkubik with Chrome v110 and V2. I have a VM that is still on v109 and all seems to be working correctly, and it logged into my account, and I am awaiting a check-in in a few hours.

**Comment by jdholtz** [comment] 2023-02-17 14:53
Thanks for letting me know. What OS are you running when you receive that error? It could be OS-dependent.

**Comment by darrylwhiting** [comment] 2023-02-17 16:00
> Thanks for letting me know. What OS are you running when you receive that error? It could be OS-dependent.

v110 is running on Windows 10 Enterprise Version 10.0.19042 (20H2).

**Comment by jdholtz** [comment] 2023-02-17 16:36
Thanks. I will try on a Windows machine soon (I’ve only tried on Linux so far).

**Comment by jdholtz** [comment] 2023-02-25 04:20
I just had the chance to try this on Windows and was able to successfully log in to my account with both Chrome v104 and Chrome v110. For reference, I was using the develop branch with `undetected_chromedriver` 3.1.7, Python 3.11, and Windows 10 Pro. 

@ctkubik are you still running into this issue with the latest Chrome version?

> Nice! I got A48 and B26.

@darrylwhiting did you get this successful check-in on Chrome v110 or v109?

**Comment by ctkubik** [comment] 2023-02-25 17:57
@jdholtz I am still getting the error.  I am using the develop branch (just downloaded), Windows 11 Pro, and Version 110.0.5481.177 (Official Build) (64-bit).  I am running Python 3.8.6.  I am wondering if that is the issue?

**Comment by jdholtz** [comment] 2023-02-25 19:59
Possibly. I’ll try to test on that version to see if I can reproduce it.

**Comment by babehboi** [comment] 2023-02-27 06:39
Hey there just chiming in. But finally got a chance to read through this thread and tested it myself on Win10 latest python and chrome and I, too, get status code: 429.

And none of my username or password uses any special characters.

**Comment by ctkubik** [comment] 2023-02-27 14:54
@jdholtz I tried to downgrade my Python install to 3.11, but now I am getting the following error.  Any thoughts?

Failed to log in to account with username ctkubik. Reason: Unknown. Status code: 429.

Exception ignored in: <function Chrome.__del__ at 0x0000029AE6735BC0>
Traceback (most recent call last):
  File "C:\Users\ctkub\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
    self.quit()
  File "C:\Users\ctkub\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
    super().quit()
  File "C:\Users\ctkub\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

**Comment by ctkubik** [comment] 2023-02-27 15:02
I was able to use a confirmation number with success.  The flights need to be checked in today, so I will test if that works.

**Comment by jdholtz** [comment] 2023-02-27 15:11
People have been getting that `handle invalid` error with Windows when the chromedriver fails. That’s an issue with undetected_chromedriver, but it doesn’t actually affect the execution of the script (it should not happen if the chromedriver doesn’t fail).

**Comment by ctkubik** [comment] 2023-03-06 17:17
![image](https://user-images.githubusercontent.com/10108275/223183006-e0a87aa7-9c97-4272-869d-001881e6700f.png)

I'm still receiving errors, but I was able to check-in and my system sent the notification.

**Comment by jdholtz** [comment] 2023-03-06 22:07
That's great to hear. I can reproduce the OSError in a Windows environment as well. This is an issue in undetected_chromedriver (see [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/955)). Since it happens after the check in, it shouldn't be an issue. Let me know if it causes actual issues with the check-in though and I will make a patch for it. For now, we can wait for a fix in undetected_chromedriver.

I'll close this issue for now because other people have had successful check-ins with Chrome v110 on Windows, Mac, and Linux as well.

**Closed by jdholtz** 2023-03-06 22:07 UTC
Labels: bug

**Comment by Obiwantje** [comment] 2023-03-11 19:19
Having the same issue here - Windows 11 - Chrome Version 111.0.5563.65 (Official Build) (64-bit)

"Failed to log in to account with username XXXXXXXXXX. Reason: Unknown. Status code: 429."
